//! GENERATED by `hostgen` from the Lean effect algebras; do not edit.
//!
//! The host traits, the request frames with their decoder, the dispatch of
//! each frame to its Rust service and the test-double stubs all follow from
//! the constructors of the algebras in `lean/VerifiedCore/Host*.lean`.

use crate::host::*;
use crate::operation::{
    file_reply, reply, scan_reply, Capabilities, Decode, Encode, EncodeReply, OperationError,
    Reader,
};

/// The relational host: transactions, raw projections, mutations and byte
/// reads. The interpreter executes requests literally; algorithms, metadata
/// interpretation and operation sequencing remain in Lean.
///
/// Transaction handles are local to one interpreter session. A failed commit
/// does not acknowledge success. Dropping a session must release its resources
/// and roll back any transaction it still owns.
#[rustfmt::skip]
pub trait Storage {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn begin(&mut self) -> Result<u64, Self::Error>;
    fn commit(&mut self, tx: u64) -> Result<(), Self::Error>;
    fn rollback(&mut self, tx: u64) -> Result<(), Self::Error>;
    fn read_rows(&mut self, tx: u64, relation: &str, columns: &[String], equals: &Fields, order: &[Order], joins: &[Join]) -> Result<Vec<Row>, Self::Error>;
    fn scan_rows(&mut self, tx: u64, relation: &str, columns: &[String], equals: &Fields, order: &[Order], joins: &[Join]) -> Result<Scan<Self::Error>, Self::Error>;
    fn upsert(&mut self, tx: u64, relation: &str, values: &Fields, conflict_columns: &[String], update_columns: &[String]) -> Result<(), Self::Error>;
    fn delete_rows(&mut self, tx: u64, relation: &str, equals: &Fields, blockers: &[Exclusion], at_most: &Fields) -> Result<u64, Self::Error>;
    fn read_bytes(&mut self, space: &str, key: &[u8]) -> Result<Option<Vec<u8>>, Self::Error>;
    fn exists_rows(&mut self, tx: u64, relation: &str, equals: &Fields) -> Result<bool, Self::Error>;
    fn snapshot(&mut self, selection: &Selection, columns: &[String]) -> Result<Scan<Self::Error>, Self::Error>;
    fn update(&mut self, tx: u64, selection: &Selection, values: &Fields) -> Result<u64, Self::Error>;
    /// Atomic INSERT SELECT with ON CONFLICT on these columns DO NOTHING.
    /// Existing rows retain every field; no replacement/update is permitted.
    fn copy_rows(&mut self, tx: u64, target: &str, source: &Selection, values: &[(String, SourceValue)], conflicts: &[String]) -> Result<u64, Self::Error>;
    fn delete(&mut self, tx: u64, selection: &Selection) -> Result<u64, Self::Error>;
    fn write(&mut self, tx: u64, relation: &str, values: &Fields, conflicts: &[String], assignments: &[(String, ConflictValue)]) -> Result<(), Self::Error>;
}

/// Non-transactional raw resources, separate from the relational capability.
/// Callers retain any required ordering guards for the entire operation.
#[rustfmt::skip]
pub trait Resources {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn read_counter(&mut self, space: &str, key: &[u8]) -> Result<u64, Self::Error>;
    fn remove_file(&mut self, space: &str, key: &[u8]) -> Result<(), Self::Error>;
}

/// Primitive cryptography, separate from storage and domain validation.
#[rustfmt::skip]
pub trait Crypto {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn validate_ed25519(&mut self, bytes: &[u8]) -> Result<bool, Self::Error>;
}

/// Session-local raw file handles. Dropping the host releases outstanding handles.
#[rustfmt::skip]
pub trait FileIO {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn open(&mut self, space: &str, key: &[u8]) -> Result<u64, FileFailure<Self::Error>>;
    fn read_at(&mut self, handle: u64, offset: u64, count: u64) -> Result<Vec<u8>, FileFailure<Self::Error>>;
    fn close(&mut self, handle: u64) -> Result<(), Self::Error>;
    /// Fill `buffer` from `offset`, returning `ShortRead` at EOF. The
    /// interpreter hands over the tail of the operation's output sink, so a
    /// transfer costs one read into the bytes the caller receives.
    fn read_into(
        &mut self,
        handle: u64,
        offset: u64,
        buffer: &mut [u8],
    ) -> Result<(), FileFailure<Self::Error>>;
}

/// Wall-clock input; the operation chooses when to observe it.
#[rustfmt::skip]
pub trait Clock {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn now_ns(&mut self) -> Result<i64, Self::Error>;
}

/// Operation-local byte sink. Appended bytes are provisional until the whole
/// operation succeeds; the caller discards the sink on failure.
#[rustfmt::skip]
pub trait Output {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn append(&mut self, bytes: &[u8]) -> Result<(), Self::Error>;
    /// Extend the sink by `count` bytes and hand them back for an in-place
    /// fill, so a file transfer lands directly in the result.
    fn grow(&mut self, count: u64) -> Result<&mut [u8], Self::Error>;
    /// Take back the last `count` bytes after a fill failed.
    fn shrink(&mut self, count: u64);
}

/// Bulk object construction over resources the requesting operation owns.
///
/// The operation decides what is built, from which opened source and into
/// which owned temporaries; the host streams the bytes, hashes them into the
/// BLAKE3 tree and lays out the Bao outboard. Neither call publishes, flushes
/// or records anything.
#[rustfmt::skip]
pub trait Construct {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn build(&mut self, source: u64, payload: u64, outboard: u64, size: u64) -> Result<Vec<u8>, Self::Error>;
    fn hash(&mut self, bytes: &[u8]) -> Result<Vec<u8>, Self::Error>;
}

/// Invocation-owned staging resources. Abandonment releases handles and
/// removes unpublished temporary names; replacement consumes temporary ownership.
#[rustfmt::skip]
pub trait TemporaryFiles {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    /// Create an empty exclusive temporary in the indicated namespace, on the
    /// same filesystem as its eventual target. Each successful call owns a fresh
    /// handle distinct from every other live resource in this invocation. Creation
    /// and live-resource registration are atomic against temporary-file sweeping.
    fn create_temporary(&mut self, space: &str) -> Result<u64, Self::Error>;
    /// Flush all previously accepted writes to the named owned temporary.
    fn flush(&mut self, handle: u64) -> Result<(), Self::Error>;
    /// Atomically replace one keyed target with the owned temporary. Success
    /// consumes the temporary; failure leaves it owned. This is not a two-file
    /// transaction, and never acknowledges parent-directory synchronization.
    fn replace(&mut self, handle: u64, space: &str, key: &[u8]) -> Result<(), Self::Error>;
    /// Idempotently close/unlink only the invocation-owned temporary. A token
    /// consumed by replace is a no-op: never unlink its published target. Failure
    /// consumes the token too; host abandonment cleanup retains any needed fallback.
    fn discard(&mut self, handle: u64) -> Result<(), Self::Error>;
    /// Distinguish a platform's lack of directory synchronization support from
    /// an actual failed synchronization. Include newly created namespace ancestor
    /// entries down to the configured durable storage root, not just the target's
    /// immediate directory. Policy for unsupported lives in Lean.
    fn sync_parent(&mut self, space: &str, key: &[u8]) -> Result<SyncStatus, Self::Error>;
}

/// Opaque counted resource leases ordered against competing deletion. Host
/// abandonment releases outstanding tokens; policy chooses their lifetime.
#[rustfmt::skip]
pub trait Lease {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    /// Register keyed protection against removal and return an owned token.
    /// Acquisition is ordered against the remover's check-and-unlink critical
    /// section. Multiple concurrent tokens are allowed; this is not an exclusive
    /// writer lock. It must not be acquired inside a database transaction.
    fn acquire(&mut self, space: &str, key: &[u8]) -> Result<u64, Self::Error>;
    /// Consume the token, including on reported failure. Abandonment releases
    /// outstanding tokens; a caller must never retry release after an error.
    fn release(&mut self, token: u64) -> Result<(), Self::Error>;
}

/// Raw input observations. Successful bounded reads may be short at EOF;
/// freeze retains an immutable copy under an invocation-owned input handle.
#[rustfmt::skip]
pub trait SourceIO {
    /// Original host error, retained without converting it into a policy result.
    type Error;
    fn stat(&mut self, space: &str, key: &[u8]) -> Result<u64, Self::Error>;
    /// Read up to count bytes at offset. For a positive count, empty means EOF;
    /// successful bytes never exceed count. Sequential offsets must also work for
    /// stream handles; unsupported random access may fail. This does not capture
    /// the rest of a file or interpret its metadata.
    fn read_some(&mut self, handle: u64, offset: u64, count: u64) -> Result<Vec<u8>, Self::Error>;
    /// Retain immutable raw bytes under a fresh invocation-owned file handle.
    /// FileIO.readAt/readSome access them; FileIO.close consumes the handle.
    fn freeze(&mut self, bytes: &[u8]) -> Result<u64, Self::Error>;
}

/// One decoded request packet. Terminal packets carry the operation's
/// result or failure; every other frame is one effect of one algebra.
#[derive(Debug)]
#[rustfmt::skip]
pub(crate) enum Frame<'a> {
    Done(&'a [u8]),
    Failure(u64, u64),
    Begin,
    Commit(u64),
    Rollback(u64),
    ReadRows(u64, String, Vec<String>, Fields, Vec<Order>, Vec<Join>),
    ScanRows(u64, String, Vec<String>, Fields, Vec<Order>, Vec<Join>),
    Upsert(u64, String, Fields, Vec<String>, Vec<String>),
    DeleteRows(u64, String, Fields, Vec<Exclusion>, Fields),
    ReadBytes(String, &'a [u8]),
    ReadInput(u64, u64, u64),
    ReadCounter(String, &'a [u8]),
    RemoveFile(String, &'a [u8]),
    ExistsRows(u64, String, Fields),
    ValidateEd25519(&'a [u8]),
    Snapshot(Selection, Vec<String>),
    Update(u64, Selection, Fields),
    CopyRows(u64, String, Selection, Vec<(String, SourceValue)>, Vec<String>),
    Delete(u64, Selection),
    Open(String, &'a [u8]),
    ReadAt(u64, u64, u64),
    Transfer(u64, u64, u64),
    Close(u64),
    NowNs,
    Append(&'a [u8]),
    Build(u64, u64, u64, u64),
    Hash(&'a [u8]),
    Write(u64, String, Fields, Vec<String>, Vec<(String, ConflictValue)>),
    CreateTemporary(String),
    Flush(u64),
    Replace(u64, String, &'a [u8]),
    Discard(u64),
    SyncParent(String, &'a [u8]),
    Acquire(String, &'a [u8]),
    Release(u64),
    Stat(String, &'a [u8]),
    ReadSome(u64, u64, u64),
    Freeze(&'a [u8]),
}

#[rustfmt::skip]
pub(crate) fn decode(packet: &[u8]) -> Result<Frame<'_>, ()> {
    let mut r = Reader(packet);
    if r.byte()? != 1 {
        return Err(());
    }
    let frame = match r.byte()? {
        0 => Frame::Done(r.byte_slice()?),
        1 => Frame::Failure(r.word()?, r.word()?),
        16 => Frame::Begin,
        17 => Frame::Commit(r.word()?),
        18 => Frame::Rollback(r.word()?),
        19 => Frame::ReadRows(r.word()?, r.string()?, r.list(Reader::string)?, r.fields()?, r.list(Reader::order)?, r.list(Reader::join)?),
        28 => Frame::ScanRows(r.word()?, r.string()?, r.list(Reader::string)?, r.fields()?, r.list(Reader::order)?, r.list(Reader::join)?),
        20 => Frame::Upsert(r.word()?, r.string()?, r.fields()?, r.list(Reader::string)?, r.list(Reader::string)?),
        21 => Frame::DeleteRows(r.word()?, r.string()?, r.fields()?, r.list(Reader::exclusion)?, r.fields()?),
        22 => Frame::ReadBytes(r.string()?, r.byte_slice()?),
        23 => Frame::ReadInput(r.word()?, r.word()?, r.word()?),
        24 => Frame::ReadCounter(r.string()?, r.byte_slice()?),
        25 => Frame::RemoveFile(r.string()?, r.byte_slice()?),
        26 => Frame::ExistsRows(r.word()?, r.string()?, r.fields()?),
        27 => Frame::ValidateEd25519(r.byte_slice()?),
        29 => Frame::Snapshot(r.selection()?, r.list(Reader::string)?),
        30 => Frame::Update(r.word()?, r.selection()?, r.fields()?),
        31 => Frame::CopyRows(r.word()?, r.string()?, r.selection()?, r.list(|r| Ok((r.string()?, r.source_value()?)))?, r.list(Reader::string)?),
        32 => Frame::Delete(r.word()?, r.selection()?),
        33 => Frame::Open(r.string()?, r.byte_slice()?),
        34 => Frame::ReadAt(r.word()?, r.word()?, r.word()?),
        52 => Frame::Transfer(r.word()?, r.word()?, r.word()?),
        35 => Frame::Close(r.word()?),
        36 => Frame::NowNs,
        37 => Frame::Append(r.byte_slice()?),
        38 => Frame::Build(r.word()?, r.word()?, r.word()?, r.word()?),
        39 => Frame::Hash(r.byte_slice()?),
        41 => Frame::Write(r.word()?, r.string()?, r.fields()?, r.list(Reader::string)?, r.assignments()?),
        42 => Frame::CreateTemporary(r.string()?),
        43 => Frame::Flush(r.word()?),
        44 => Frame::Replace(r.word()?, r.string()?, r.byte_slice()?),
        45 => Frame::Discard(r.word()?),
        46 => Frame::SyncParent(r.string()?, r.byte_slice()?),
        47 => Frame::Acquire(r.string()?, r.byte_slice()?),
        48 => Frame::Release(r.word()?),
        49 => Frame::Stat(r.string()?, r.byte_slice()?),
        50 => Frame::ReadSome(r.word()?, r.word()?, r.word()?),
        51 => Frame::Freeze(r.byte_slice()?),
        _ => return Err(()),
    };
    r.end()?;
    Ok(frame)
}

/// Serve one effect frame with the host it routes to. Terminal frames and
/// the effects the interpreter loop serves itself are refused here.
#[rustfmt::skip]
pub(crate) fn dispatch<S: Storage>(
    storage: &mut S,
    capabilities: &mut Capabilities<'_, S::Error>,
    frame: Frame<'_>,
    errors: &mut Vec<Option<S::Error>>,
) -> Result<Vec<u8>, OperationError<S::Error>> {
    Ok(match frame {
        Frame::Begin => {
            reply(16, storage.begin(), errors, EncodeReply::encode)
        }
        Frame::Commit(a0) => {
            reply(17, storage.commit(a0), errors, EncodeReply::encode)
        }
        Frame::Rollback(a0) => {
            reply(18, storage.rollback(a0), errors, EncodeReply::encode)
        }
        Frame::ReadRows(a0, a1, a2, a3, a4, a5) => {
            reply(19, storage.read_rows(a0, &a1, &a2, &a3, &a4, &a5), errors, EncodeReply::encode)
        }
        Frame::ScanRows(a0, a1, a2, a3, a4, a5) => {
            scan_reply(28, storage.scan_rows(a0, &a1, &a2, &a3, &a4, &a5), errors)
        }
        Frame::Upsert(a0, a1, a2, a3, a4) => {
            reply(20, storage.upsert(a0, &a1, &a2, &a3, &a4), errors, EncodeReply::encode)
        }
        Frame::DeleteRows(a0, a1, a2, a3, a4) => {
            reply(21, storage.delete_rows(a0, &a1, &a2, &a3, &a4), errors, EncodeReply::encode)
        }
        Frame::ReadBytes(a0, a1) => {
            reply(22, storage.read_bytes(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::ReadCounter(a0, a1) => {
            let host = capabilities.resources.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(24, host.read_counter(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::RemoveFile(a0, a1) => {
            let host = capabilities.resources.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(25, host.remove_file(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::ExistsRows(a0, a1, a2) => {
            reply(26, storage.exists_rows(a0, &a1, &a2), errors, EncodeReply::encode)
        }
        Frame::ValidateEd25519(a0) => {
            let host = capabilities.crypto.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(27, host.validate_ed25519(a0), errors, EncodeReply::encode)
        }
        Frame::Snapshot(a0, a1) => {
            scan_reply(29, storage.snapshot(&a0, &a1), errors)
        }
        Frame::Update(a0, a1, a2) => {
            reply(30, storage.update(a0, &a1, &a2), errors, EncodeReply::encode)
        }
        Frame::CopyRows(a0, a1, a2, a3, a4) => {
            reply(31, storage.copy_rows(a0, &a1, &a2, &a3, &a4), errors, EncodeReply::encode)
        }
        Frame::Delete(a0, a1) => {
            reply(32, storage.delete(a0, &a1), errors, EncodeReply::encode)
        }
        Frame::Open(a0, a1) => {
            let host = capabilities.files.as_deref_mut().ok_or(OperationError::Protocol)?;
            file_reply(33, host.open(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::ReadAt(a0, a1, a2) => {
            let host = capabilities.files.as_deref_mut().ok_or(OperationError::Protocol)?;
            file_reply(34, host.read_at(a0, a1, a2), errors, EncodeReply::encode)
        }
        Frame::Close(a0) => {
            let host = capabilities.files.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(35, host.close(a0), errors, EncodeReply::encode)
        }
        Frame::NowNs => {
            let host = capabilities.clock.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(36, host.now_ns(), errors, EncodeReply::encode)
        }
        Frame::Build(a0, a1, a2, a3) => {
            let host = capabilities.construct.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(38, host.build(a0, a1, a2, a3), errors, EncodeReply::encode)
        }
        Frame::Hash(a0) => {
            let host = capabilities.construct.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(39, host.hash(a0), errors, EncodeReply::encode)
        }
        Frame::Write(a0, a1, a2, a3, a4) => {
            reply(41, storage.write(a0, &a1, &a2, &a3, &a4), errors, EncodeReply::encode)
        }
        Frame::CreateTemporary(a0) => {
            let host = capabilities.temporary.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(42, host.create_temporary(&a0), errors, EncodeReply::encode)
        }
        Frame::Flush(a0) => {
            let host = capabilities.temporary.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(43, host.flush(a0), errors, EncodeReply::encode)
        }
        Frame::Replace(a0, a1, a2) => {
            let host = capabilities.temporary.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(44, host.replace(a0, &a1, a2), errors, EncodeReply::encode)
        }
        Frame::Discard(a0) => {
            let host = capabilities.temporary.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(45, host.discard(a0), errors, EncodeReply::encode)
        }
        Frame::SyncParent(a0, a1) => {
            let host = capabilities.temporary.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(46, host.sync_parent(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::Acquire(a0, a1) => {
            let host = capabilities.leases.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(47, host.acquire(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::Release(a0) => {
            let host = capabilities.leases.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(48, host.release(a0), errors, EncodeReply::encode)
        }
        Frame::Stat(a0, a1) => {
            let host = capabilities.source.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(49, host.stat(&a0, a1), errors, EncodeReply::encode)
        }
        Frame::ReadSome(a0, a1, a2) => {
            let host = capabilities.source.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(50, host.read_some(a0, a1, a2), errors, EncodeReply::encode)
        }
        Frame::Freeze(a0) => {
            let host = capabilities.source.as_deref_mut().ok_or(OperationError::Protocol)?;
            reply(51, host.freeze(a0), errors, EncodeReply::encode)
        }
        _ => return Err(OperationError::Protocol),
    })
}

/// Fills a test double's `impl` with the host methods the operation under
/// test never requests; each panics with its name if it is reached.
#[macro_export]
macro_rules! host_unexpected {
    (begin) => {
        fn begin(&mut self) -> Result<u64, Self::Error> {
            panic!("unexpected begin")
        }
    };
    (commit) => {
        fn commit(&mut self, _: u64) -> Result<(), Self::Error> {
            panic!("unexpected commit")
        }
    };
    (rollback) => {
        fn rollback(&mut self, _: u64) -> Result<(), Self::Error> {
            panic!("unexpected rollback")
        }
    };
    (read_rows) => {
        fn read_rows(&mut self, _: u64, _: &str, _: &[String], _: &$crate::host::Fields, _: &[$crate::host::Order], _: &[$crate::host::Join]) -> Result<Vec<$crate::host::Row>, Self::Error> {
            panic!("unexpected read_rows")
        }
    };
    (scan_rows) => {
        fn scan_rows(&mut self, _: u64, _: &str, _: &[String], _: &$crate::host::Fields, _: &[$crate::host::Order], _: &[$crate::host::Join]) -> Result<$crate::host::Scan<Self::Error>, Self::Error> {
            panic!("unexpected scan_rows")
        }
    };
    (upsert) => {
        fn upsert(&mut self, _: u64, _: &str, _: &$crate::host::Fields, _: &[String], _: &[String]) -> Result<(), Self::Error> {
            panic!("unexpected upsert")
        }
    };
    (delete_rows) => {
        fn delete_rows(&mut self, _: u64, _: &str, _: &$crate::host::Fields, _: &[$crate::host::Exclusion], _: &$crate::host::Fields) -> Result<u64, Self::Error> {
            panic!("unexpected delete_rows")
        }
    };
    (read_bytes) => {
        fn read_bytes(&mut self, _: &str, _: &[u8]) -> Result<Option<Vec<u8>>, Self::Error> {
            panic!("unexpected read_bytes")
        }
    };
    (exists_rows) => {
        fn exists_rows(&mut self, _: u64, _: &str, _: &$crate::host::Fields) -> Result<bool, Self::Error> {
            panic!("unexpected exists_rows")
        }
    };
    (snapshot) => {
        fn snapshot(&mut self, _: &$crate::host::Selection, _: &[String]) -> Result<$crate::host::Scan<Self::Error>, Self::Error> {
            panic!("unexpected snapshot")
        }
    };
    (update) => {
        fn update(&mut self, _: u64, _: &$crate::host::Selection, _: &$crate::host::Fields) -> Result<u64, Self::Error> {
            panic!("unexpected update")
        }
    };
    (copy_rows) => {
        fn copy_rows(&mut self, _: u64, _: &str, _: &$crate::host::Selection, _: &[(String, $crate::host::SourceValue)], _: &[String]) -> Result<u64, Self::Error> {
            panic!("unexpected copy_rows")
        }
    };
    (delete) => {
        fn delete(&mut self, _: u64, _: &$crate::host::Selection) -> Result<u64, Self::Error> {
            panic!("unexpected delete")
        }
    };
    (write) => {
        fn write(&mut self, _: u64, _: &str, _: &$crate::host::Fields, _: &[String], _: &[(String, $crate::host::ConflictValue)]) -> Result<(), Self::Error> {
            panic!("unexpected write")
        }
    };
    (read_counter) => {
        fn read_counter(&mut self, _: &str, _: &[u8]) -> Result<u64, Self::Error> {
            panic!("unexpected read_counter")
        }
    };
    (remove_file) => {
        fn remove_file(&mut self, _: &str, _: &[u8]) -> Result<(), Self::Error> {
            panic!("unexpected remove_file")
        }
    };
    (validate_ed25519) => {
        fn validate_ed25519(&mut self, _: &[u8]) -> Result<bool, Self::Error> {
            panic!("unexpected validate_ed25519")
        }
    };
    (open) => {
        fn open(&mut self, _: &str, _: &[u8]) -> Result<u64, $crate::host::FileFailure<Self::Error>> {
            panic!("unexpected open")
        }
    };
    (read_at) => {
        fn read_at(&mut self, _: u64, _: u64, _: u64) -> Result<Vec<u8>, $crate::host::FileFailure<Self::Error>> {
            panic!("unexpected read_at")
        }
    };
    (close) => {
        fn close(&mut self, _: u64) -> Result<(), Self::Error> {
            panic!("unexpected close")
        }
    };
    (now_ns) => {
        fn now_ns(&mut self) -> Result<i64, Self::Error> {
            panic!("unexpected now_ns")
        }
    };
    (append) => {
        fn append(&mut self, _: &[u8]) -> Result<(), Self::Error> {
            panic!("unexpected append")
        }
    };
    (build) => {
        fn build(&mut self, _: u64, _: u64, _: u64, _: u64) -> Result<Vec<u8>, Self::Error> {
            panic!("unexpected build")
        }
    };
    (hash) => {
        fn hash(&mut self, _: &[u8]) -> Result<Vec<u8>, Self::Error> {
            panic!("unexpected hash")
        }
    };
    (create_temporary) => {
        fn create_temporary(&mut self, _: &str) -> Result<u64, Self::Error> {
            panic!("unexpected create_temporary")
        }
    };
    (flush) => {
        fn flush(&mut self, _: u64) -> Result<(), Self::Error> {
            panic!("unexpected flush")
        }
    };
    (replace) => {
        fn replace(&mut self, _: u64, _: &str, _: &[u8]) -> Result<(), Self::Error> {
            panic!("unexpected replace")
        }
    };
    (discard) => {
        fn discard(&mut self, _: u64) -> Result<(), Self::Error> {
            panic!("unexpected discard")
        }
    };
    (sync_parent) => {
        fn sync_parent(&mut self, _: &str, _: &[u8]) -> Result<$crate::host::SyncStatus, Self::Error> {
            panic!("unexpected sync_parent")
        }
    };
    (acquire) => {
        fn acquire(&mut self, _: &str, _: &[u8]) -> Result<u64, Self::Error> {
            panic!("unexpected acquire")
        }
    };
    (release) => {
        fn release(&mut self, _: u64) -> Result<(), Self::Error> {
            panic!("unexpected release")
        }
    };
    (stat) => {
        fn stat(&mut self, _: &str, _: &[u8]) -> Result<u64, Self::Error> {
            panic!("unexpected stat")
        }
    };
    (read_some) => {
        fn read_some(&mut self, _: u64, _: u64, _: u64) -> Result<Vec<u8>, Self::Error> {
            panic!("unexpected read_some")
        }
    };
    (freeze) => {
        fn freeze(&mut self, _: &[u8]) -> Result<u64, Self::Error> {
            panic!("unexpected freeze")
        }
    };
    ($($method:ident),+ $(,)?) => {
        $($crate::host_unexpected!($method);)+
    };
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub enum CellType {
    Null,
    Integer,
    Real,
    Text,
    Blob,
}

#[rustfmt::skip]
impl Encode for CellType {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Null => out.push(0),
            Self::Integer => out.push(1),
            Self::Real => out.push(2),
            Self::Text => out.push(3),
            Self::Blob => out.push(4),
        }
    }
}

#[rustfmt::skip]
impl Decode for CellType {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Null,
            1 => Self::Integer,
            2 => Self::Real,
            3 => Self::Text,
            4 => Self::Blob,
            _ => return Err(()),
        })
    }
}

/// A public holder value, not a parsed database spelling. In particular an
/// unknown holder whose spelling resembles a role does not acquire that role's
/// meaning, and an explicitly constructed role may name the empty space.
#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum PinHolder {
    Operator,
    Source(String),
    Replica(String),
    Other(String),
}

#[rustfmt::skip]
impl Encode for PinHolder {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Operator => out.push(0),
            Self::Source(a0) => {
                out.push(1);
                a0.encode(out);
            }
            Self::Replica(a0) => {
                out.push(2);
                a0.encode(out);
            }
            Self::Other(a0) => {
                out.push(3);
                a0.encode(out);
            }
        }
    }
}

#[rustfmt::skip]
impl Decode for PinHolder {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Operator,
            1 => Self::Source(Decode::decode(r)?),
            2 => Self::Replica(Decode::decode(r)?),
            3 => Self::Other(Decode::decode(r)?),
            _ => return Err(()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum IngestInput {
    Bytes(u64),
    File,
}

#[rustfmt::skip]
impl Encode for IngestInput {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Bytes(a0) => {
                out.push(0);
                a0.encode(out);
            }
            Self::File => out.push(1),
        }
    }
}

#[rustfmt::skip]
impl Decode for IngestInput {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Bytes(Decode::decode(r)?),
            1 => Self::File,
            _ => return Err(()),
        })
    }
}

/// A domain-level outcome, independent of internal algorithm phases.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub enum Outcome {
    Skipped,
    Writing,
    ProtectedClaim,
    Applied,
}

#[rustfmt::skip]
impl Encode for Outcome {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Skipped => out.push(0),
            Self::Writing => out.push(1),
            Self::ProtectedClaim => out.push(2),
            Self::Applied => out.push(3),
        }
    }
}

#[rustfmt::skip]
impl Decode for Outcome {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Skipped,
            1 => Self::Writing,
            2 => Self::ProtectedClaim,
            3 => Self::Applied,
            _ => return Err(()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum OriginError {
    Label(String),
    Domain(String),
    KeyDecode,
    KeyData,
    Shape(String),
}

#[rustfmt::skip]
impl Encode for OriginError {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Label(a0) => {
                out.push(0);
                a0.encode(out);
            }
            Self::Domain(a0) => {
                out.push(1);
                a0.encode(out);
            }
            Self::KeyDecode => out.push(2),
            Self::KeyData => out.push(3),
            Self::Shape(a0) => {
                out.push(4);
                a0.encode(out);
            }
        }
    }
}

#[rustfmt::skip]
impl Decode for OriginError {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Label(Decode::decode(r)?),
            1 => Self::Domain(Decode::decode(r)?),
            2 => Self::KeyDecode,
            3 => Self::KeyData,
            4 => Self::Shape(Decode::decode(r)?),
            _ => return Err(()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum LookupDomainError {
    KeyTooLong(u64),
    MissingNode(Vec<u8>),
    MissingValue(Vec<u8>),
    Decode(String),
    DepthExceeded,
}

#[rustfmt::skip]
impl Encode for LookupDomainError {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::KeyTooLong(a0) => {
                out.push(0);
                a0.encode(out);
            }
            Self::MissingNode(a0) => {
                out.push(1);
                a0.encode(out);
            }
            Self::MissingValue(a0) => {
                out.push(2);
                a0.encode(out);
            }
            Self::Decode(a0) => {
                out.push(3);
                a0.encode(out);
            }
            Self::DepthExceeded => out.push(4),
        }
    }
}

#[rustfmt::skip]
impl Decode for LookupDomainError {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::KeyTooLong(Decode::decode(r)?),
            1 => Self::MissingNode(Decode::decode(r)?),
            2 => Self::MissingValue(Decode::decode(r)?),
            3 => Self::Decode(Decode::decode(r)?),
            4 => Self::DepthExceeded,
            _ => return Err(()),
        })
    }
}

/// Malformed metadata or a column of the wrong storage class, as pin
/// acquisition and deletion report it.
#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum LifecycleDomainError {
    Malformed,
    ColumnType {
        index: u64,
        column: String,
        actual: CellType,
    },
}

#[rustfmt::skip]
impl Encode for LifecycleDomainError {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Malformed => out.push(0),
            Self::ColumnType { index, column, actual } => {
                out.push(1);
                index.encode(out);
                column.encode(out);
                actual.encode(out);
            }
        }
    }
}

#[rustfmt::skip]
impl Decode for LifecycleDomainError {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Malformed,
            1 => Self::ColumnType {
                index: Decode::decode(r)?,
                column: Decode::decode(r)?,
                actual: Decode::decode(r)?,
            },
            _ => return Err(()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum IngestDomainError {
    Malformed,
    ColumnType {
        index: u64,
        column: String,
        actual: CellType,
    },
    /// The row's claim cannot yield to the offered size.
    SizeMismatch {
        root: Vec<u8>,
        recorded: u64,
        offered: u64,
    },
    /// The platform cannot synchronize directories and the policy requires it.
    DirectorySyncUnsupported,
}

#[rustfmt::skip]
impl Encode for IngestDomainError {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Malformed => out.push(0),
            Self::ColumnType { index, column, actual } => {
                out.push(1);
                index.encode(out);
                column.encode(out);
                actual.encode(out);
            }
            Self::SizeMismatch { root, recorded, offered } => {
                out.push(2);
                root.encode(out);
                recorded.encode(out);
                offered.encode(out);
            }
            Self::DirectorySyncUnsupported => out.push(3),
        }
    }
}

#[rustfmt::skip]
impl Decode for IngestDomainError {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Malformed,
            1 => Self::ColumnType {
                index: Decode::decode(r)?,
                column: Decode::decode(r)?,
                actual: Decode::decode(r)?,
            },
            2 => Self::SizeMismatch {
                root: Decode::decode(r)?,
                recorded: Decode::decode(r)?,
                offered: Decode::decode(r)?,
            },
            3 => Self::DirectorySyncUnsupported,
            _ => return Err(()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum ReadDomainError {
    MissingBlob,
    Range {
        start: u64,
        stop: u64,
        size: u64,
    },
    Unavailable,
    ShortInline,
    Malformed,
    ColumnType {
        index: u64,
        column: String,
        actual: CellType,
    },
    Column {
        column: String,
        reason: String,
    },
}

#[rustfmt::skip]
impl Encode for ReadDomainError {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::MissingBlob => out.push(0),
            Self::Range { start, stop, size } => {
                out.push(1);
                start.encode(out);
                stop.encode(out);
                size.encode(out);
            }
            Self::Unavailable => out.push(2),
            Self::ShortInline => out.push(3),
            Self::Malformed => out.push(4),
            Self::ColumnType { index, column, actual } => {
                out.push(5);
                index.encode(out);
                column.encode(out);
                actual.encode(out);
            }
            Self::Column { column, reason } => {
                out.push(6);
                column.encode(out);
                reason.encode(out);
            }
        }
    }
}

#[rustfmt::skip]
impl Decode for ReadDomainError {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::MissingBlob,
            1 => Self::Range {
                start: Decode::decode(r)?,
                stop: Decode::decode(r)?,
                size: Decode::decode(r)?,
            },
            2 => Self::Unavailable,
            3 => Self::ShortInline,
            4 => Self::Malformed,
            5 => Self::ColumnType {
                index: Decode::decode(r)?,
                column: Decode::decode(r)?,
                actual: Decode::decode(r)?,
            },
            6 => Self::Column {
                column: Decode::decode(r)?,
                reason: Decode::decode(r)?,
            },
            _ => return Err(()),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum HistoryDomainError {
    Malformed,
    ColumnType {
        index: u64,
        column: String,
        actual: CellType,
    },
    InvalidText(Vec<u8>),
    Column {
        column: String,
        reason: String,
    },
    Origin(OriginError),
}

#[rustfmt::skip]
impl Encode for HistoryDomainError {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Malformed => out.push(0),
            Self::ColumnType { index, column, actual } => {
                out.push(1);
                index.encode(out);
                column.encode(out);
                actual.encode(out);
            }
            Self::InvalidText(a0) => {
                out.push(2);
                a0.encode(out);
            }
            Self::Column { column, reason } => {
                out.push(3);
                column.encode(out);
                reason.encode(out);
            }
            Self::Origin(a0) => {
                out.push(4);
                a0.encode(out);
            }
        }
    }
}

#[rustfmt::skip]
impl Decode for HistoryDomainError {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Malformed,
            1 => Self::ColumnType {
                index: Decode::decode(r)?,
                column: Decode::decode(r)?,
                actual: Decode::decode(r)?,
            },
            2 => Self::InvalidText(Decode::decode(r)?),
            3 => Self::Column {
                column: Decode::decode(r)?,
                reason: Decode::decode(r)?,
            },
            4 => Self::Origin(Decode::decode(r)?),
            _ => return Err(()),
        })
    }
}

/// A whole ingested object.
#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub struct Ingested {
    pub root: Vec<u8>,
    pub size: u64,
}

#[rustfmt::skip]
impl Encode for Ingested {
    fn encode(&self, out: &mut Vec<u8>) {
        self.root.encode(out);
        self.size.encode(out);
    }
}

#[rustfmt::skip]
impl Decode for Ingested {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(Self {
            root: Decode::decode(r)?,
            size: Decode::decode(r)?,
        })
    }
}

/// What a commit settled: the size the row records now, and whether every
/// group of the object is present.
#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub struct Committed {
    pub size: u64,
    pub complete: bool,
}

#[rustfmt::skip]
impl Encode for Committed {
    fn encode(&self, out: &mut Vec<u8>) {
        self.size.encode(out);
        self.complete.encode(out);
    }
}

#[rustfmt::skip]
impl Decode for Committed {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(Self {
            size: Decode::decode(r)?,
            complete: Decode::decode(r)?,
        })
    }
}

/// Every command the host can start. The arguments are the command's whole
/// input apart from the borrowed byte inputs (`Storage.readInput`) a run supplies.
#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub(crate) enum Command {
    /// Pin or take possession of an object for a holder.
    Acquire {
        root: Vec<u8>,
        holder: String,
        now: i64,
        possession: bool,
    },
    /// Delete an object, or only collect it when unused since `before`.
    Delete {
        root: Vec<u8>,
        before: Option<i64>,
    },
    /// Release one holder's claim.
    Unpin {
        root: Vec<u8>,
        holder: PinHolder,
    },
    /// Expire due claims, for one holder or for all.
    Expire {
        holder: Option<PinHolder>,
        now: i64,
    },
    /// Read the whole object or a range of it into the run's output sink.
    Read {
        root: Vec<u8>,
        range: Option<(u64, u64)>,
    },
    /// Ingest the run's `input` capability as a whole object.
    Ingest {
        input: IngestInput,
        now: i64,
        cache: bool,
        allow_unsupported: bool,
    },
    /// Commit verified groups of an object.
    CommitGroups {
        root: Vec<u8>,
        spans: Vec<(u64, u64)>,
        size: u64,
        inline: Option<Vec<u8>>,
        now: i64,
        cache: bool,
    },
    /// Refuse a size the object's row cannot yield to.
    AdmitSize {
        root: Vec<u8>,
        size: u64,
    },
    /// Look a key up in a trie; the key is the run's first byte input.
    TrieGet {
        root: Vec<u8>,
        key_size: u64,
    },
    /// Retire head history of an origin recorded before `before`.
    PruneHistory {
        origin: String,
        before: i64,
    },
}

#[rustfmt::skip]
impl Encode for Command {
    fn encode(&self, out: &mut Vec<u8>) {
        match self {
            Self::Acquire { root, holder, now, possession } => {
                out.push(0);
                root.encode(out);
                holder.encode(out);
                now.encode(out);
                possession.encode(out);
            }
            Self::Delete { root, before } => {
                out.push(1);
                root.encode(out);
                before.encode(out);
            }
            Self::Unpin { root, holder } => {
                out.push(2);
                root.encode(out);
                holder.encode(out);
            }
            Self::Expire { holder, now } => {
                out.push(3);
                holder.encode(out);
                now.encode(out);
            }
            Self::Read { root, range } => {
                out.push(4);
                root.encode(out);
                range.encode(out);
            }
            Self::Ingest { input, now, cache, allow_unsupported } => {
                out.push(5);
                input.encode(out);
                now.encode(out);
                cache.encode(out);
                allow_unsupported.encode(out);
            }
            Self::CommitGroups { root, spans, size, inline, now, cache } => {
                out.push(6);
                root.encode(out);
                spans.encode(out);
                size.encode(out);
                inline.encode(out);
                now.encode(out);
                cache.encode(out);
            }
            Self::AdmitSize { root, size } => {
                out.push(7);
                root.encode(out);
                size.encode(out);
            }
            Self::TrieGet { root, key_size } => {
                out.push(8);
                root.encode(out);
                key_size.encode(out);
            }
            Self::PruneHistory { origin, before } => {
                out.push(9);
                origin.encode(out);
                before.encode(out);
            }
        }
    }
}

#[rustfmt::skip]
impl Decode for Command {
    fn decode(r: &mut Reader<'_>) -> Result<Self, ()> {
        Ok(match r.byte()? {
            0 => Self::Acquire {
                root: Decode::decode(r)?,
                holder: Decode::decode(r)?,
                now: Decode::decode(r)?,
                possession: Decode::decode(r)?,
            },
            1 => Self::Delete {
                root: Decode::decode(r)?,
                before: Decode::decode(r)?,
            },
            2 => Self::Unpin {
                root: Decode::decode(r)?,
                holder: Decode::decode(r)?,
            },
            3 => Self::Expire {
                holder: Decode::decode(r)?,
                now: Decode::decode(r)?,
            },
            4 => Self::Read {
                root: Decode::decode(r)?,
                range: Decode::decode(r)?,
            },
            5 => Self::Ingest {
                input: Decode::decode(r)?,
                now: Decode::decode(r)?,
                cache: Decode::decode(r)?,
                allow_unsupported: Decode::decode(r)?,
            },
            6 => Self::CommitGroups {
                root: Decode::decode(r)?,
                spans: Decode::decode(r)?,
                size: Decode::decode(r)?,
                inline: Decode::decode(r)?,
                now: Decode::decode(r)?,
                cache: Decode::decode(r)?,
            },
            7 => Self::AdmitSize {
                root: Decode::decode(r)?,
                size: Decode::decode(r)?,
            },
            8 => Self::TrieGet {
                root: Decode::decode(r)?,
                key_size: Decode::decode(r)?,
            },
            9 => Self::PruneHistory {
                origin: Decode::decode(r)?,
                before: Decode::decode(r)?,
            },
            _ => return Err(()),
        })
    }
}
