//! The SQLite store: open, configuration, device keys, and the trie node store.

use std::{
    path::{Path, PathBuf},
    str::FromStr,
    sync::{Mutex, MutexGuard, PoisonError},
};

use iroh_base::SecretKey;
use rusqlite::{params, Connection, OptionalExtension};
use synch_core::{Hash, NodeId, OriginId};
use synch_mpt::NodeStore;

use crate::{
    error::{Result, StoreError},
    schema::{Migration, MIGRATIONS},
};

/// Directory under the data dir holding blob payloads and outboards (§6.2).
pub const CAS_DIR: &str = "store";
/// Directory under the CAS root holding half-written ingests (§7.1).
///
/// Its own directory, not the CAS root beside the shards. A staging file in the
/// root is a *regular file* where the orphan sweep expects a shard directory,
/// which makes `read_dir` on it fail with `NotADirectory` and would kill the
/// sweep permanently — and only that sweep can remove the file. Under a name of
/// its own the sweep has one rule about one place, and the CAS root holds
/// nothing but directories by construction.
pub const STAGING_DIR: &str = "incoming";
/// The database file name (§10).
pub const DB_FILE: &str = "synchronicity.db";

/// Restricts the data directory to owner-only access (§3). No-op off Unix.
fn harden_permissions(data_dir: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(data_dir, std::fs::Permissions::from_mode(0o700));
    }
    #[cfg(not(unix))]
    let _ = data_dir;
}

/// Restricts the database and its WAL/SHM sidecars to owner-only. No-op off
/// Unix. Called after `init`, once WAL mode has created the sidecars.
fn harden_db_files(data_dir: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for name in [DB_FILE, "synchronicity.db-wal", "synchronicity.db-shm"] {
            let path = data_dir.join(name);
            if path.exists() {
                let _ = std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600));
            }
        }
    }
    #[cfg(not(unix))]
    let _ = data_dir;
}

/// The state of a locally held device key.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyState {
    /// Generated by `key rotate` and waiting for `key activate` (§3.4).
    ///
    /// Its own state, because both neighbors mislead: this key is not signing
    /// anything yet, and calling it "retiring" would tell the operator that the
    /// key they just minted is on its way out.
    Staged,
    /// The key currently used for signing and for the primary endpoint.
    Active,
    /// A key kept alive through a rotation window (§3.4).
    Retiring,
}

impl KeyState {
    /// The `state` column value.
    pub fn as_str(self) -> &'static str {
        match self {
            KeyState::Staged => "staged",
            KeyState::Active => "active",
            KeyState::Retiring => "retiring",
        }
    }

    /// Parses the `state` column value.
    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "staged" => Ok(KeyState::Staged),
            "active" => Ok(KeyState::Active),
            "retiring" => Ok(KeyState::Retiring),
            other => Err(StoreError::column("device_keys.state", other)),
        }
    }
}

/// The config key holding the one membership domain (§3.1).
const DOMAIN_KEY: &str = "membership.domain";

/// One identity this node adopted from its membership zone (§3.1).
#[derive(Debug, Clone)]
pub struct IdentityAdoption {
    /// When the adoption was committed, unix nanos.
    pub at: i64,
    /// What this node published as before it, or `None` for its first name.
    pub previous: Option<OriginId>,
    /// The name it took.
    pub adopted: OriginId,
    /// The device key the zone bound to that name.
    pub node_id: NodeId,
    /// The zone that named it, or `''` when the name was dropped for a key
    /// identity.
    pub domain: String,
}

/// A locally held device key.
#[derive(Debug, Clone)]
pub struct DeviceKey {
    /// The public half, which is also the iroh endpoint id.
    pub node_id: NodeId,
    /// The secret half.
    pub secret: SecretKey,
    /// Whether the key is active or retiring.
    pub state: KeyState,
    /// When the key was generated, in unix nanoseconds.
    pub created_at: i64,
}

/// Whether this thread is inside a [`Store::transaction`] scope.
///
/// [`Store::transaction`] holds the connection `MutexGuard` for the whole of
/// its closure and `std::sync::Mutex` is not reentrant, so any `Store` method
/// called from inside that closure blocks the thread against a lock it is
/// itself holding. Nothing prevented it: the `Store` handle is in scope at
/// every call site (`self.store.transaction(|txn| …)`), `Txn` deliberately
/// exposes a narrower surface than `Store` — no `blob`, no `pinned_blobs`, no
/// `prune_history_before` — so reaching for the wrong one is easy, and the
/// compiler has nothing to say about it.
///
/// What makes that worth ten lines of guard is the failure mode. A deadlock is
/// not a panic: the thread simply stops, so a test that exercised the path
/// would hang until the harness timed out rather than fail with a location.
/// This turns it into a named assertion, in debug and test builds only.
#[cfg(debug_assertions)]
mod reentry {
    use std::cell::Cell;

    thread_local! {
        static DEPTH: Cell<usize> = const { Cell::new(0) };
    }

    /// Marks the calling thread as inside a transaction until it is dropped.
    pub(super) struct Scope;

    impl Scope {
        pub(super) fn enter() -> Scope {
            DEPTH.with(|d| d.set(d.get() + 1));
            Scope
        }
    }

    impl Drop for Scope {
        fn drop(&mut self) {
            DEPTH.with(|d| d.set(d.get().saturating_sub(1)));
        }
    }

    pub(super) fn active() -> bool {
        DEPTH.with(|d| d.get()) > 0
    }
}

#[cfg(not(debug_assertions))]
mod reentry {
    pub(super) struct Scope;

    impl Scope {
        pub(super) fn enter() -> Scope {
            Scope
        }
    }

    pub(super) fn active() -> bool {
        false
    }
}

/// Whether this thread is inside a transaction scope.
fn in_transaction() -> bool {
    reentry::active()
}

/// The node's metadata store.
///
/// All writes funnel through one mutex-guarded connection, which is how the
/// §10 "single writer task" discipline is realized here: every multi-step state
/// change (head flips, publish batches) runs inside one SQLite transaction on
/// that connection, so no partial state is ever observable.
#[derive(Debug)]
pub struct Store {
    conn: Mutex<Connection>,
    data_dir: PathBuf,
    /// Roots a full walk has established this store holds entirely.
    ///
    /// "Do I hold this whole trie?" is asked on every `Hello` (§5.1) and
    /// answered by walking everything reachable — so without this a converged
    /// cluster pays for the size of its metadata on every anti-entropy round,
    /// on both sides, forever. A content-addressed root that was complete
    /// stays complete, so the walk is owed once per root and not once per
    /// exchange. Process-local and rebuilt on demand: losing it costs one
    /// walk, never correctness.
    complete_roots: Mutex<std::collections::HashSet<Hash>>,
    /// Objects a CAS write is currently between its first byte and its commit.
    ///
    /// The collector and the writers agree about *rows* — every blob row goes
    /// through the one connection — and did not agree about *bytes*.
    /// `write_slice` and `write_proof` do all their file IO with no lock held
    /// (creating, growing, decoding, two fsyncs and two parent fsyncs) and only
    /// then take the connection to commit the bitmap. So a sweep could decide an
    /// object was collectable, delete its row, unlink its files, and have the
    /// writer's commit land *after* the unlinks — leaving a row that claims
    /// verified groups with no payload behind them. That state advertises the
    /// object to the whole membership through `local_ad`, fails every read, and
    /// self-heals never: `gc_content` skips it because an entry names it,
    /// `gc_orphans` skips it because it *has* a row, and `write_slice`
    /// early-returns when the row says complete.
    ///
    /// `delete_blob_if_collectable` held its guard across the unlinks to close
    /// exactly this window and could not: holding it only forces the writer's
    /// commit to land later, which is the wrong side. What was missing is a fact
    /// the collector could read — "somebody is writing this object" — so here it
    /// is. Held for the whole write, consulted by both sweeps under the
    /// connection guard, and in memory because the CAS has one writer process:
    /// the daemon.
    writing: Mutex<std::collections::HashMap<Hash, usize>>,
}

/// Marks an object as being written, until dropped.
///
/// A count rather than a flag: two fetches of one root — a mirror pass and a
/// `synch cat`, say — overlap legitimately, and the first to finish must not
/// clear the mark the second is relying on.
#[derive(Debug)]
pub struct WriteLease<'a> {
    store: &'a Store,
    root: Hash,
}

impl Drop for WriteLease<'_> {
    fn drop(&mut self) {
        let mut writing = self.store.writing();
        if let Some(count) = writing.get_mut(&self.root) {
            *count -= 1;
            if *count == 0 {
                writing.remove(&self.root);
            }
        }
    }
}

/// How many roots the completeness memo holds before it is dropped wholesale.
///
/// One entry per root this node has confirmed, which is one per published head
/// and one per peer head adopted; a long-lived node would otherwise accumulate
/// them without bound. Dropping the lot costs a walk on the roots still in use
/// and nothing else, which is why there is no LRU here.
const COMPLETE_ROOTS_MAX: usize = 4096;

impl Store {
    /// Opens (creating if needed) the store rooted at `data_dir`.
    pub fn open(data_dir: impl AsRef<Path>) -> Result<Store> {
        let data_dir = data_dir.as_ref().to_path_buf();
        std::fs::create_dir_all(&data_dir)?;
        std::fs::create_dir_all(data_dir.join(CAS_DIR))?;
        // The DB holds this node's device secret key and the S3 access keys, so
        // it must not be world-readable (§3). `synch init` hardens the datadir,
        // but the daemon can be pointed at a fresh dir (or a restored backup)
        // without it — so the store defends its own files unconditionally.
        harden_permissions(&data_dir);
        let conn = Connection::open(data_dir.join(DB_FILE))?;
        let store = Store {
            conn: Mutex::new(conn),
            data_dir,
            complete_roots: Mutex::new(std::collections::HashSet::new()),
            writing: Mutex::new(std::collections::HashMap::new()),
        };
        store.init()?;
        // WAL/SHM sidecars are created by `init` (WAL mode); tighten them too.
        harden_db_files(&store.data_dir);
        Ok(store)
    }

    /// Opens a purely in-memory store backed by a temporary CAS directory.
    ///
    /// Intended for tests; `data_dir` still receives blob payloads.
    pub fn open_in_memory(data_dir: impl AsRef<Path>) -> Result<Store> {
        let data_dir = data_dir.as_ref().to_path_buf();
        std::fs::create_dir_all(data_dir.join(CAS_DIR))?;
        let store = Store {
            conn: Mutex::new(Connection::open_in_memory()?),
            data_dir,
            complete_roots: Mutex::new(std::collections::HashSet::new()),
            writing: Mutex::new(std::collections::HashMap::new()),
        };
        store.init()?;
        Ok(store)
    }

    fn init(&self) -> Result<()> {
        let mut conn = self.conn();
        conn.pragma_update(None, "foreign_keys", "ON")?;
        // WAL keeps readers off the writer's back; NORMAL is the §10 setting.
        let _: String = conn.query_row("PRAGMA journal_mode=WAL", [], |row| row.get(0))?;
        conn.pragma_update(None, "synchronous", "NORMAL")?;
        conn.pragma_update(None, "busy_timeout", 5_000)?;
        migrate(&mut conn, MIGRATIONS)?;
        Ok(())
    }

    /// The data directory.
    pub fn data_dir(&self) -> &Path {
        &self.data_dir
    }

    /// The CAS root directory.
    pub fn cas_dir(&self) -> PathBuf {
        self.data_dir.join(CAS_DIR)
    }

    /// The directory ingests stream into before renaming onto a content
    /// address (§7.1).
    pub fn staging_dir(&self) -> PathBuf {
        self.cas_dir().join(STAGING_DIR)
    }

    pub(crate) fn conn(&self) -> MutexGuard<'_, Connection> {
        debug_assert!(
            !in_transaction(),
            "Store::conn() was called from inside a transaction. The connection \
             mutex is not reentrant, so this deadlocks: use the `Txn` the closure \
             was handed, not the `Store` it came from."
        );
        // The other half of the same idea (§10). Every acquisition here is a
        // wait on the one global connection mutex, and a long holder — a publish
        // batch, a GC pass, a slice commit — parks whoever is waiting for as
        // long as it runs. On a runtime worker that is the endpoint, the control
        // socket and every timer in the process, which is why the rule is
        // "blocking work goes to the blocking pool" and why it needs a checker
        // rather than a convention: four audit passes moved call sites off the
        // runtime and each left some behind, because a violation compiles,
        // passes its tests, and only shows up as a daemon that goes quiet.
        synch_core::assert_off_runtime("a Store connection acquisition");
        self.conn.lock().unwrap_or_else(PoisonError::into_inner)
    }

    /// Runs `f` against the raw transaction handle, committing on `Ok`.
    ///
    /// The store's own multi-statement writes use this; callers outside the
    /// crate get [`Store::transaction`], which hands out a [`Txn`] scope rather
    /// than a `rusqlite` type.
    pub(crate) fn with_tx<T>(
        &self,
        f: impl FnOnce(&rusqlite::Transaction<'_>) -> Result<T>,
    ) -> Result<T> {
        let conn = self.conn();
        let _scope = reentry::Scope::enter();
        let tx = conn.unchecked_transaction()?;
        let out = f(&tx)?;
        tx.commit()?;
        Ok(out)
    }

    /// Runs `f` in a transaction that takes SQLite's write lock up front.
    ///
    /// [`Store::with_tx`] begins deferred, which acquires the read lock first
    /// and upgrades it on the first write. That is right for a transaction that
    /// only writes, and wrong for one that *reads and then writes what it read*:
    /// under multi-process WAL, another process committing in between makes the
    /// upgrade fail with `SQLITE_BUSY_SNAPSHOT` rather than wait, because the
    /// snapshot the read saw is no longer the tip. Nothing is corrupted, but the
    /// work the transaction was about to record is lost and the caller has to
    /// find out and repeat it.
    ///
    /// `BEGIN IMMEDIATE` takes the write lock at the start instead, so the
    /// contention is handled by `busy_timeout` like any other — a wait rather
    /// than a failure. The read-union-write bitmap commit
    /// ([`Store::commit_groups`](crate::Store)) is the path that needs it.
    pub(crate) fn with_immediate_tx<T>(
        &self,
        f: impl FnOnce(&rusqlite::Transaction<'_>) -> Result<T>,
    ) -> Result<T> {
        let mut conn = self.conn();
        let _scope = reentry::Scope::enter();
        let tx = conn.transaction_with_behavior(rusqlite::TransactionBehavior::Immediate)?;
        let out = f(&tx)?;
        tx.commit()?;
        Ok(out)
    }

    /// Runs `f` inside a single SQLite transaction, committing on `Ok` and
    /// rolling the whole thing back on `Err`.
    ///
    /// This is the unit of atomicity §10 asks for: "every multi-step state
    /// change (head flips, publish batches) is a single transaction and no
    /// partial state is ever observable". The scope handed to `f` is a [`Txn`],
    /// which is both a [`NodeStore`] — so trie writes join the transaction —
    /// and the head, history, and materialization surface a publish or a
    /// promotion needs. No `rusqlite` type crosses the boundary.
    ///
    /// The error type is the caller's, so an engine or a net operation can run
    /// its own failures through the same rollback: anything that converts from
    /// [`StoreError`] works.
    ///
    /// The transaction begins **immediate**. Every caller here reads and then
    /// writes what it read — a publish reads the head it is about to displace,
    /// a promotion reads the pending slot, GC reads the roots it marks from —
    /// which is the one shape `BEGIN DEFERRED` handles badly: it takes the read
    /// lock first and upgrades on the first write, and under multi-process WAL
    /// another process committing in between fails the upgrade outright with
    /// `SQLITE_BUSY_SNAPSHOT` rather than waiting, because the snapshot the read
    /// saw is no longer the tip. Nothing is corrupted, but the work is lost and
    /// the caller has to notice. Taking the write lock up front turns that into
    /// an ordinary `busy_timeout` wait. In-process the connection mutex already
    /// serializes writers, so this costs nothing there.
    pub fn transaction<T, E>(
        &self,
        f: impl FnOnce(&Txn<'_>) -> std::result::Result<T, E>,
    ) -> std::result::Result<T, E>
    where
        E: From<StoreError>,
    {
        let mut conn = self.conn();
        let _scope = reentry::Scope::enter();
        let tx = conn
            .transaction_with_behavior(rusqlite::TransactionBehavior::Immediate)
            .map_err(StoreError::from)?;
        // On `Err` the `Transaction` is dropped without a commit, which is a
        // rollback: nothing the closure wrote is observable afterwards.
        let out = f(&Txn {
            tx: &tx,
            store: self,
        })?;
        tx.commit().map_err(StoreError::from)?;
        Ok(out)
    }

    // ---- config -----------------------------------------------------------

    /// Reads a config value.
    pub fn config(&self, key: &str) -> Result<Option<String>> {
        Ok(self
            .conn()
            .query_row(
                "SELECT value FROM config WHERE key = ?1",
                params![key],
                |r| r.get(0),
            )
            .optional()?)
    }

    /// Writes a config value.
    pub fn set_config(&self, key: &str, value: &str) -> Result<()> {
        self.conn().execute(
            "INSERT INTO config (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            params![key, value],
        )?;
        Ok(())
    }

    /// Appends one newline-separated record to a config value, creating the
    /// value if it does not exist yet.
    ///
    /// A config row that holds a *list* — the S3 gateway's bucket map and its
    /// access keys (§9.4) — is read and written by more than one process, and
    /// a read-modify-write of the whole list silently drops whichever concurrent
    /// edit commits first. One SQL statement cannot: the append happens inside
    /// the database, under the same single connection every other write goes
    /// through, so two appends interleave instead of overwriting each other.
    pub fn append_config(&self, key: &str, record: &str) -> Result<()> {
        self.conn().execute(
            "INSERT INTO config (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = value || char(10) || excluded.value",
            params![key, record],
        )?;
        Ok(())
    }

    /// Deletes a config value.
    pub fn clear_config(&self, key: &str) -> Result<()> {
        self.conn()
            .execute("DELETE FROM config WHERE key = ?1", params![key])?;
        Ok(())
    }

    /// This node's own [`OriginId`], if `synch init` has run.
    pub fn self_origin(&self) -> Result<Option<OriginId>> {
        match self.config("self_origin_id")? {
            None => Ok(None),
            Some(text) => OriginId::from_str(&text)
                .map(Some)
                .map_err(|e| StoreError::column("config.self_origin_id", e.to_string())),
        }
    }

    /// Sets this node's own [`OriginId`].
    pub fn set_self_origin(&self, origin: &OriginId) -> Result<()> {
        self.set_config("self_origin_id", &origin.canonical())
    }

    /// The membership domain this node belongs to, if it has one (§3.1).
    ///
    /// Held separately from `self_origin_id` even though it is that origin's
    /// `@domain` half, because it has to be readable *before* there is a name
    /// to read it out of: a node that has never identified has only this.
    pub fn membership_domain(&self) -> Result<Option<String>> {
        self.config(DOMAIN_KEY)
    }

    /// Sets the membership domain, or clears it when given `None`.
    pub fn set_membership_domain(&self, domain: Option<&str>) -> Result<()> {
        match domain {
            Some(domain) => self.set_config(DOMAIN_KEY, domain),
            None => self.clear_config(DOMAIN_KEY),
        }
    }

    /// Every identity this node has adopted from its zone, oldest first (§3.1).
    pub fn identity_history(&self) -> Result<Vec<IdentityAdoption>> {
        let conn = self.conn();
        let mut stmt = conn.prepare(
            "SELECT at, previous, adopted, node_id, domain FROM identity_history ORDER BY at",
        )?;
        let rows = stmt.query_map([], |row| {
            Ok((
                row.get::<_, i64>(0)?,
                row.get::<_, Option<String>>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, Vec<u8>>(3)?,
                row.get::<_, String>(4)?,
            ))
        })?;
        let mut out = Vec::new();
        for row in rows {
            let (at, previous, adopted, node_id, domain) = row?;
            out.push(IdentityAdoption {
                at,
                previous: previous
                    .map(|text| origin_column(text, "identity_history.previous"))
                    .transpose()?,
                adopted: origin_column(adopted, "identity_history.adopted")?,
                node_id: key_column(node_id, "identity_history.node_id")?,
                domain,
            });
        }
        Ok(out)
    }

    // ---- device keys ------------------------------------------------------

    /// Stores a device key.
    pub fn add_device_key(&self, secret: &SecretKey, state: KeyState, now: i64) -> Result<()> {
        self.conn().execute(
            "INSERT INTO device_keys (node_id, secret_key, state, created_at) VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT(node_id) DO UPDATE SET state = excluded.state",
            params![
                secret.public().as_bytes().to_vec(),
                secret.to_bytes().to_vec(),
                state.as_str(),
                now
            ],
        )?;
        Ok(())
    }

    /// Every locally held device key, active ones first.
    pub fn device_keys(&self) -> Result<Vec<DeviceKey>> {
        let conn = self.conn();
        let mut stmt = conn.prepare(
            "SELECT node_id, secret_key, state, created_at FROM device_keys
             ORDER BY state = 'active' DESC, created_at DESC",
        )?;
        let rows = stmt.query_map([], |row| {
            Ok((
                row.get::<_, Vec<u8>>(0)?,
                row.get::<_, Vec<u8>>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, i64>(3)?,
            ))
        })?;
        let mut out = Vec::new();
        for row in rows {
            let (node_id, secret, state, created_at) = row?;
            let node_id: [u8; 32] = node_id
                .try_into()
                .map_err(|_| StoreError::column("device_keys.node_id", "not 32 bytes"))?;
            let secret: [u8; 32] = secret
                .try_into()
                .map_err(|_| StoreError::column("device_keys.secret_key", "not 32 bytes"))?;
            out.push(DeviceKey {
                node_id: NodeId::from_bytes(&node_id)
                    .map_err(|e| StoreError::column("device_keys.node_id", e.to_string()))?,
                secret: SecretKey::from_bytes(&secret),
                state: KeyState::parse(&state)?,
                created_at,
            });
        }
        Ok(out)
    }

    /// The key currently used for signing (§3.4: exactly one at any moment).
    pub fn active_device_key(&self) -> Result<Option<DeviceKey>> {
        Ok(self
            .device_keys()?
            .into_iter()
            .find(|k| k.state == KeyState::Active))
    }

    /// Marks a device key as retiring or active.
    pub fn set_device_key_state(&self, node_id: &NodeId, state: KeyState) -> Result<()> {
        set_device_key_state_in(&self.conn(), node_id, state)
    }

    /// Deletes a retired device key's secret (§3.4 step 4).
    pub fn remove_device_key(&self, node_id: &NodeId) -> Result<()> {
        self.conn().execute(
            "DELETE FROM device_keys WHERE node_id = ?1",
            params![node_id.as_bytes().to_vec()],
        )?;
        Ok(())
    }
}

/// One SQLite transaction, as the rest of the workspace sees it.
///
/// Everything a publish or a head flip touches — trie nodes and values, the
/// two head slots, `head_history`, and the materialized `entries` /
/// `blob_providers` views — is reachable from here and lands in the same
/// commit. Obtained only from [`Store::transaction`], which is what makes "one
/// transaction" a property of the type rather than a convention.
#[derive(Debug)]
pub struct Txn<'a> {
    tx: &'a rusqlite::Transaction<'a>,
    store: &'a Store,
}

impl Txn<'_> {
    /// The underlying connection, for the store's own statement helpers.
    pub(crate) fn conn(&self) -> &Connection {
        self.tx
    }

    /// Sets this node's own [`OriginId`], inside the transaction.
    pub fn set_self_origin(&self, origin: &OriginId) -> Result<()> {
        self.conn().execute(
            "INSERT INTO config (key, value) VALUES ('self_origin_id', ?1)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            params![origin.canonical()],
        )?;
        Ok(())
    }

    /// Marks a device key as retiring or active, inside the transaction.
    ///
    /// A rotation moves two keys' states and must move both or neither: §3.4
    /// says exactly one key is active at any moment, and nothing in the schema
    /// enforces it. As two autocommit statements, a crash or a `BUSY` between
    /// them left the retiring key retired and the incoming key still staged —
    /// zero active keys, so [`Store::active_device_key`] answers `None` and the
    /// daemon refuses to open, which is also the only way to run the command
    /// that would repair it.
    pub fn set_device_key_state(&self, node_id: &NodeId, state: KeyState) -> Result<()> {
        set_device_key_state_in(self.conn(), node_id, state)
    }

    /// Sets or clears the membership domain, inside the transaction.
    pub fn set_membership_domain(&self, domain: Option<&str>) -> Result<()> {
        match domain {
            Some(domain) => self.conn().execute(
                "INSERT INTO config (key, value) VALUES (?1, ?2)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                params![DOMAIN_KEY, domain],
            )?,
            None => self
                .conn()
                .execute("DELETE FROM config WHERE key = ?1", params![DOMAIN_KEY])?,
        };
        Ok(())
    }

    /// Drops the publishing floor, inside the transaction.
    ///
    /// A floor is a promise about seqs under one name (§3.4); carried across an
    /// identity migration it would floor history nobody holds under the name
    /// being adopted.
    pub fn clear_publish_floor(&self) -> Result<()> {
        self.conn()
            .execute("DELETE FROM config WHERE key = 'publish_floor'", [])?;
        Ok(())
    }

    /// Records an identity adoption, inside the transaction (§3.1).
    ///
    /// `previous` is `None` for a node's first name, which is an adoption like
    /// any other: the zone named a key that had no name, and the trail has to
    /// say when that happened as much as it says when a name was replaced.
    pub fn record_identity_adoption(
        &self,
        previous: Option<&OriginId>,
        adopted: &OriginId,
        node_id: &NodeId,
        domain: &str,
        at: i64,
    ) -> Result<()> {
        self.conn().execute(
            "INSERT INTO identity_history (at, previous, adopted, node_id, domain)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![
                at,
                previous.map(|origin| origin.canonical()),
                adopted.canonical(),
                node_id.as_bytes().as_slice(),
                domain,
            ],
        )?;
        Ok(())
    }

    /// Drops every dns binding that did not come from `domain`, inside the
    /// transaction.
    ///
    /// A node resolves the zone that names it and no other (§3.1), so on
    /// adopting a name the bindings vouched for by the zone being left have no
    /// authority behind them any more — and nothing else would remove them
    /// before their own expiry.
    pub fn delete_dns_bindings_other_than(&self, domain: &str) -> Result<usize> {
        Ok(self.conn().execute(
            "DELETE FROM bindings WHERE source = 'dns' AND domain <> ?1",
            params![domain],
        )?)
    }

    /// Forgets what peers advertised for an origin, inside the transaction.
    pub fn clear_observed_head(&self, origin: &OriginId) -> Result<()> {
        self.conn().execute(
            "DELETE FROM observed_heads WHERE origin_id = ?1",
            params![origin.canonical()],
        )?;
        Ok(())
    }
}

fn set_device_key_state_in(conn: &Connection, node_id: &NodeId, state: KeyState) -> Result<()> {
    conn.execute(
        "UPDATE device_keys SET state = ?2 WHERE node_id = ?1",
        params![node_id.as_bytes().to_vec(), state.as_str()],
    )?;
    Ok(())
}

impl NodeStore for Txn<'_> {
    type Error = StoreError;

    /// Reads the store's completeness memo, which was established by walks over
    /// committed data and says nothing about this transaction's own writes.
    fn is_known_complete(&self, root: &Hash) -> Result<bool> {
        self.store.is_known_complete(root)
    }

    /// Deliberately records nothing. A scope that can still roll back must not
    /// vouch for nodes the commit might never land.
    fn note_complete(&self, _root: &Hash) -> Result<()> {
        Ok(())
    }

    fn get_node(&self, hash: &Hash) -> Result<Option<Vec<u8>>> {
        get_node_in(self.conn(), hash)
    }

    fn put_node(&self, hash: &Hash, data: &[u8]) -> Result<()> {
        put_node_in(self.conn(), hash, data)
    }

    fn get_value(&self, hash: &Hash) -> Result<Option<Vec<u8>>> {
        get_value_in(self.conn(), hash)
    }

    fn put_value(&self, hash: &Hash, data: &[u8]) -> Result<()> {
        put_value_in(self.conn(), hash, data)
    }

    fn has_node(&self, hash: &Hash) -> Result<bool> {
        has_node_in(self.conn(), hash)
    }

    fn has_value(&self, hash: &Hash) -> Result<bool> {
        has_value_in(self.conn(), hash)
    }

    fn is_redacted(&self, hash: &Hash) -> Result<bool> {
        is_redacted_in(self.conn(), hash)
    }

    fn note_redacted(&self, hash: &Hash) -> Result<()> {
        note_redacted_in(self.conn(), hash)
    }
}

// ---- migrations ------------------------------------------------------------

/// The version a database is stamped with, or 0 for an empty one.
///
/// A database with a `config` table but no stamp is refused rather than
/// guessed at: every database this software has ever written stamps itself
/// inside the transaction that shaped it (§10), so an unstamped one is not a
/// version this build can reason about.
fn stamped_version(conn: &Connection) -> Result<u32> {
    let bootstrapped = conn
        .query_row(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'config'",
            [],
            |_| Ok(()),
        )
        .optional()?
        .is_some();
    if !bootstrapped {
        return Ok(0);
    }
    let stamp: Option<String> = conn
        .query_row(
            "SELECT value FROM config WHERE key = 'schema_version'",
            [],
            |row| row.get(0),
        )
        .optional()?;
    match stamp {
        None => Err(StoreError::invalid(
            "this database has a config table but no schema_version stamp, \
             so its shape cannot be determined",
        )),
        Some(text) => text.trim().parse::<u32>().map_err(|_| {
            StoreError::invalid(format!(
                "database schema version {text:?} is not a version number this build understands"
            ))
        }),
    }
}

/// Replays `chain` from wherever `conn` currently is up to its end (§10).
///
/// Each step is one transaction that also carries the `schema_version` stamp,
/// so an interrupted upgrade leaves the database at some version of the chain
/// and never between two. A database stamped past the end of the chain is
/// refused: this build cannot know what it would be reading.
///
/// Takes the chain as an argument rather than reading [`MIGRATIONS`] directly
/// so that tests can drive a chain whose steps fail on purpose.
pub(crate) fn migrate(conn: &mut Connection, chain: &[Migration]) -> Result<u32> {
    let target = chain.len() as u32;
    let found = stamped_version(conn)?;
    if found > target {
        return Err(StoreError::invalid(format!(
            "database schema version {found} is newer than this build supports (expected {target}): \
             upgrade synchronicity rather than downgrading the database"
        )));
    }
    for version in found..target {
        let tx = conn.transaction()?;
        match &chain[version as usize] {
            Migration::Sql(sql) => tx.execute_batch(sql)?,
            Migration::Rust { name, run } => run(&tx).map_err(|e| {
                StoreError::invalid(format!(
                    "migration to version {} ({name}): {e}",
                    version + 1
                ))
            })?,
        }
        // Inside the same transaction as the change it describes: that is what
        // makes a crash land exactly on a version.
        tx.execute(
            "INSERT INTO config (key, value) VALUES ('schema_version', ?1)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            params![(version + 1).to_string()],
        )?;
        tx.commit()?;
    }
    if found != target {
        tracing::info!(from = found, to = target, "database schema migrated");
    }
    Ok(target)
}

// ---- the trie node store ---------------------------------------------------

impl NodeStore for Store {
    type Error = StoreError;

    fn get_node(&self, hash: &Hash) -> Result<Option<Vec<u8>>> {
        get_node_in(&self.conn(), hash)
    }

    fn put_node(&self, hash: &Hash, data: &[u8]) -> Result<()> {
        put_node_in(&self.conn(), hash, data)
    }

    fn get_value(&self, hash: &Hash) -> Result<Option<Vec<u8>>> {
        get_value_in(&self.conn(), hash)
    }

    fn put_value(&self, hash: &Hash, data: &[u8]) -> Result<()> {
        put_value_in(&self.conn(), hash, data)
    }

    fn has_node(&self, hash: &Hash) -> Result<bool> {
        has_node_in(&self.conn(), hash)
    }

    fn has_value(&self, hash: &Hash) -> Result<bool> {
        has_value_in(&self.conn(), hash)
    }

    fn is_known_complete(&self, root: &Hash) -> Result<bool> {
        Ok(self.complete_roots().contains(root))
    }

    fn note_complete(&self, root: &Hash) -> Result<()> {
        let mut roots = self.complete_roots();
        if roots.len() >= COMPLETE_ROOTS_MAX {
            roots.clear();
        }
        roots.insert(*root);
        Ok(())
    }

    /// Redaction is durable, unlike the completeness memo above.
    ///
    /// A boundary a peer reported is the answer to "may I see this?", and that
    /// answer outlives the process: forgetting it across a restart puts the
    /// walk back to asking for what it will be refused, once per round, until
    /// §5.2's abandonment clause retires a head that was never incomplete.
    fn is_redacted(&self, hash: &Hash) -> Result<bool> {
        is_redacted_in(&self.conn(), hash)
    }

    fn note_redacted(&self, hash: &Hash) -> Result<()> {
        note_redacted_in(&self.conn(), hash)
    }
}

impl Store {
    fn complete_roots(&self) -> MutexGuard<'_, std::collections::HashSet<Hash>> {
        self.complete_roots
            .lock()
            .unwrap_or_else(PoisonError::into_inner)
    }

    fn writing(&self) -> MutexGuard<'_, std::collections::HashMap<Hash, usize>> {
        self.writing.lock().unwrap_or_else(PoisonError::into_inner)
    }

    /// Marks `root` as being written until the returned lease is dropped.
    ///
    /// Taken *before* the first byte and held past the commit, which is what
    /// makes the mark meaningful: a sweep that reads it while holding the
    /// connection guard either sees the mark — and leaves the object alone — or
    /// runs entirely before the writer started, in which case the writer opens
    /// the payload fresh and its row describes what it actually wrote.
    ///
    /// Which is why the mark is taken *through* the connection guard, briefly,
    /// rather than on the lease map alone. The sweeps hold that guard from
    /// their `is_being_written` check through the unlink, but nothing on a
    /// writer's path from the lease to its first byte touches it — so a lease
    /// taken on the map alone could land after the check and rename a payload
    /// into place before the unlink, leaving a row that claims a complete
    /// object with no bytes. Every caller takes the lease with no connection
    /// held (each reads its row after, through `blob`), so this only orders
    /// them; it never nests.
    pub(crate) fn lease_write(&self, root: &Hash) -> WriteLease<'_> {
        let _ordered_against_the_sweeps = self.conn();
        *self.writing().entry(*root).or_insert(0) += 1;
        WriteLease {
            store: self,
            root: *root,
        }
    }

    /// True if a CAS write is in flight for `root`.
    ///
    /// Read by both sweeps while they hold the connection guard, so the answer
    /// cannot go stale between the decision and the unlink.
    pub(crate) fn is_being_written(&self, root: &Hash) -> bool {
        self.writing().contains_key(root)
    }

    /// Keeps only the memo entries for roots still in the retained set.
    ///
    /// A sweep takes the nodes of every root it did not mark from, so a memo
    /// entry for one of those becomes a standing lie: `Hello` would go on
    /// advertising a trie this node can no longer serve. Dropping the whole
    /// memo is the safe version of that — but the memo is exactly the answer
    /// §5.1 exists to avoid recomputing on every exchange, and GC runs every
    /// five minutes against a thirty-second anti-entropy interval, so clearing
    /// it wholesale gives the cost back on roughly one round in ten, forever.
    /// Retaining the marked roots keeps the optimization and the honesty.
    pub fn retain_complete_roots(&self, keep: &std::collections::HashSet<Hash>) {
        self.complete_roots().retain(|root| keep.contains(root));
    }
}

// The trie node store, expressed against a connection so that both the store
// and a [`Txn`] scope run exactly the same statements.

fn get_node_in(conn: &Connection, hash: &Hash) -> Result<Option<Vec<u8>>> {
    Ok(conn
        .query_row(
            "SELECT data FROM trie_nodes WHERE hash = ?1",
            params![hash.as_bytes().to_vec()],
            |r| r.get(0),
        )
        .optional()?)
}

fn put_node_in(conn: &Connection, hash: &Hash, data: &[u8]) -> Result<()> {
    conn.execute(
        "INSERT OR IGNORE INTO trie_nodes (hash, data) VALUES (?1, ?2)",
        params![hash.as_bytes().to_vec(), data],
    )?;
    Ok(())
}

fn get_value_in(conn: &Connection, hash: &Hash) -> Result<Option<Vec<u8>>> {
    Ok(conn
        .query_row(
            "SELECT data FROM trie_values WHERE hash = ?1",
            params![hash.as_bytes().to_vec()],
            |r| r.get(0),
        )
        .optional()?)
}

fn put_value_in(conn: &Connection, hash: &Hash, data: &[u8]) -> Result<()> {
    conn.execute(
        "INSERT OR IGNORE INTO trie_values (hash, data) VALUES (?1, ?2)",
        params![hash.as_bytes().to_vec(), data],
    )?;
    Ok(())
}

fn has_node_in(conn: &Connection, hash: &Hash) -> Result<bool> {
    Ok(conn
        .query_row(
            "SELECT 1 FROM trie_nodes WHERE hash = ?1",
            params![hash.as_bytes().to_vec()],
            |_| Ok(()),
        )
        .optional()?
        .is_some())
}

fn has_value_in(conn: &Connection, hash: &Hash) -> Result<bool> {
    Ok(conn
        .query_row(
            "SELECT 1 FROM trie_values WHERE hash = ?1",
            params![hash.as_bytes().to_vec()],
            |_| Ok(()),
        )
        .optional()?
        .is_some())
}

fn is_redacted_in(conn: &Connection, hash: &Hash) -> Result<bool> {
    Ok(conn
        .query_row(
            "SELECT 1 FROM redacted_nodes WHERE hash = ?1",
            params![hash.as_bytes().to_vec()],
            |_| Ok(()),
        )
        .optional()?
        .is_some())
}

fn note_redacted_in(conn: &Connection, hash: &Hash) -> Result<()> {
    conn.execute(
        "INSERT OR IGNORE INTO redacted_nodes (hash) VALUES (?1)",
        params![hash.as_bytes().to_vec()],
    )?;
    Ok(())
}

/// Reads a 32-byte hash column.
pub(crate) fn hash_column(bytes: Vec<u8>, column: &'static str) -> Result<Hash> {
    Hash::from_slice(&bytes).map_err(|_| StoreError::column(column, "not 32 bytes"))
}

/// Reads a 32-byte device-key column.
pub(crate) fn key_column(bytes: Vec<u8>, column: &'static str) -> Result<NodeId> {
    let arr: [u8; 32] = bytes
        .try_into()
        .map_err(|_| StoreError::column(column, "not 32 bytes"))?;
    NodeId::from_bytes(&arr).map_err(|e| StoreError::column(column, e.to_string()))
}

/// Reads an origin-id column.
pub(crate) fn origin_column(text: String, column: &'static str) -> Result<OriginId> {
    OriginId::from_str(&text).map_err(|e| StoreError::column(column, e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::SCHEMA_VERSION;
    use crate::testutil;
    use rusqlite::OptionalExtension;
    use synch_mpt::Trie;

    /// The config surface round-trips through a reopen, and the self-origin is one config key written by typed wrappers (§10.3).
    #[test]
    fn config_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        {
            let store = Store::open(dir.path()).unwrap();
            assert_eq!(store.config("missing").unwrap(), None);
            store.set_config("k", "v1").unwrap();
            store.set_config("k", "v2").unwrap();
            assert_eq!(store.config("k").unwrap().as_deref(), Some("v2"));
            store.clear_config("k").unwrap();
            assert_eq!(store.config("k").unwrap(), None);
            store.set_config("hello", "world").unwrap();
        }
        let store = Store::open(dir.path()).unwrap();
        assert_eq!(
            store.config("hello").unwrap().as_deref(),
            Some("world"),
            "persists across a reopen"
        );
        assert!(dir.path().join(DB_FILE).exists());
        assert!(dir.path().join(CAS_DIR).is_dir());
        assert_eq!(store.self_origin().unwrap(), None);
        let origin = OriginId::named("nas", "cluster.example.com").unwrap();
        store.set_self_origin(&origin).unwrap();
        assert_eq!(store.self_origin().unwrap(), Some(origin));
    }

    /// A list-valued config row grows by appending, and an append never rewrites what is already there (§9.4).
    #[test]
    fn config_records_append() {
        let (_d, store) = testutil::store();
        store
            .append_config("s3.buckets", "photos\tmedia\tnewest")
            .unwrap();
        assert_eq!(
            store.config("s3.buckets").unwrap().as_deref(),
            Some("photos\tmedia\tnewest"),
            "the first append creates the row without a leading separator"
        );
        store
            .append_config("s3.buckets", "docs\tpapers\tstrict")
            .unwrap();
        assert_eq!(
            store
                .config("s3.buckets")
                .unwrap()
                .unwrap()
                .lines()
                .collect::<Vec<_>>(),
            vec!["photos\tmedia\tnewest", "docs\tpapers\tstrict"]
        );
    }

    /// Active-first ordering, exactly-one-active rotation, secret round-trip, and removal — the device-key lifecycle (§3.4).
    #[test]
    fn device_keys_round_trip() {
        let (_d, store) = testutil::store();
        let old = SecretKey::generate();
        let new = SecretKey::generate();
        store.add_device_key(&old, KeyState::Active, 1).unwrap();
        assert_eq!(
            store.active_device_key().unwrap().unwrap().node_id,
            old.public()
        );
        store
            .set_device_key_state(&old.public(), KeyState::Retiring)
            .unwrap();
        store.add_device_key(&new, KeyState::Active, 2).unwrap();
        let keys = store.device_keys().unwrap();
        assert_eq!(keys.len(), 2);
        assert_eq!(keys[0].node_id, new.public());
        assert_eq!(keys[0].state, KeyState::Active);
        assert_eq!(
            store.active_device_key().unwrap().unwrap().node_id,
            new.public()
        );
        assert_eq!(keys[0].secret.to_bytes(), new.to_bytes());
        store.remove_device_key(&old.public()).unwrap();
        assert_eq!(store.device_keys().unwrap().len(), 1);
    }

    /// Store's NodeStore impl against a real trie: inserts, completeness, point lookups, iteration.
    #[test]
    fn store_is_a_trie_node_store() {
        let (_d, store) = testutil::store();
        let trie = Trie::new(&store);
        let mut root = Hash::EMPTY;
        for i in 0..50u8 {
            root = trie.insert(root, &[i], &[i; 200]).unwrap();
        }
        assert!(trie.is_complete(root).unwrap());
        assert_eq!(trie.get(root, &[7]).unwrap().unwrap(), [7u8; 200].to_vec());
        assert_eq!(trie.iter(root).unwrap().len(), 50);
    }

    /// A refusal is remembered through either handle and across a reopen (§5.5): the fetch loop records through `Store` and the walk reads back through a `Txn`, and both must answer.
    #[test]
    fn a_refusal_is_remembered_by_both_handles_and_across_a_reopen() {
        use synch_mpt::NodeStore;
        let dir = tempfile::tempdir().unwrap();
        let withheld = Hash::new(b"withheld");
        let other = Hash::new(b"other");
        {
            let store = Store::open(dir.path()).unwrap();
            assert!(!store.is_redacted(&withheld).unwrap());
            store.note_redacted(&withheld).unwrap();
            assert!(store.is_redacted(&withheld).unwrap());
            assert!(!store.is_redacted(&other).unwrap());
            store
                .transaction(|txn| {
                    assert!(txn.is_redacted(&withheld).unwrap());
                    txn.note_redacted(&other)
                })
                .unwrap();
            assert!(store.is_redacted(&other).unwrap());
            store.note_redacted(&withheld).unwrap(); // noting twice is not an error
        }
        let store = Store::open(dir.path()).unwrap();
        assert!(store.is_redacted(&withheld).unwrap());
        assert!(store.is_redacted(&other).unwrap());
    }

    /// §10: trie writes, head, history and materialization commit together or not at all, through the public Txn surface.
    #[test]
    fn a_transaction_scope_writes_the_trie_and_the_heads_together() {
        let (_d, store) = testutil::store();
        let origin = OriginId::named("nas", "x.example").unwrap();
        let key = SecretKey::generate();
        let seed = |txn: &Txn| -> Result<Hash> {
            let trie = Trie::new(txn);
            let root = trie.insert(Hash::EMPTY, b"k", b"v")?;
            let head = synch_core::SignedHead::sign(&key, origin.clone(), 1, root, 0);
            txn.put_head(crate::heads::Slot::Complete, &head, 0, 0)?;
            txn.record_history(&head, 0)?;
            Ok(root)
        };
        let err = store
            .transaction(|txn| -> Result<()> {
                seed(txn)?;
                Err(StoreError::invalid("boom"))
            })
            .unwrap_err()
            .to_string();
        assert!(err.contains("boom"), "{err}");
        assert!(store.complete_head(&origin).unwrap().is_none());
        assert!(store.head_history(&origin).unwrap().is_empty());
        assert_eq!(
            store.trie_stats().unwrap().nodes,
            0,
            "trie writes roll back too"
        );
        // The same body, committed, leaves all three visible together.
        let root = store.transaction(seed).unwrap();
        assert_eq!(store.complete_head(&origin).unwrap().unwrap().root, root);
        assert_eq!(store.head_history(&origin).unwrap().len(), 1);
        assert!(NodeStore::has_node(&store, &root).unwrap());
    }

    /// Too-new, unparseable, or unstamped: the migration gate refuses to open.
    #[test]
    fn schema_version_mismatch_is_refused() {
        for v in [Some("999"), Some("tomorrow"), None] {
            let dir = tempfile::tempdir().unwrap();
            let store = Store::open(dir.path()).unwrap();
            match v {
                Some(v) => store.set_config("schema_version", v).unwrap(),
                None => store.clear_config("schema_version").unwrap(),
            }
            drop(store);
            let err = Store::open(dir.path());
            if v == Some("999") {
                assert!(err
                    .unwrap_err()
                    .to_string()
                    .contains("newer than this build"));
            } else {
                assert!(err.is_err());
            }
        }
    }

    /// Every object `sqlite_master` holds, DDL normalized so comments and layout do not count as differences.
    fn objects(conn: &Connection) -> Vec<(String, String, String)> {
        let mut stmt = conn.prepare("SELECT type, name, COALESCE(sql, '') FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type, name").unwrap();
        let rows = stmt
            .query_map([], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    normalize_ddl(&row.get::<_, String>(2)?),
                ))
            })
            .unwrap();
        rows.collect::<rusqlite::Result<Vec<_>>>().unwrap()
    }

    /// Drops SQL comments and normalizes `(`, `)`, `,` spacing, so two spellings of the same declaration compare equal.
    fn normalize_ddl(sql: &str) -> String {
        let stripped: String = sql
            .lines()
            .map(|line| match line.find("--") {
                Some(i) => &line[..i],
                None => line,
            })
            .collect::<Vec<_>>()
            .join(" ");
        let spaced: String = stripped
            .chars()
            .flat_map(|c| match c {
                '(' | ')' | ',' => vec![' ', c, ' '],
                other => vec![other],
            })
            .collect();
        spaced.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    /// The `sql` block of `DESIGN.md` §10, read from the file rather than copied: a copy is exactly the drift this test exists to catch.
    fn design_schema() -> String {
        let text = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("..")
                .join("..")
                .join("DESIGN.md"),
        )
        .unwrap_or_else(|e| panic!("cannot read DESIGN.md: {e}"));
        let mut blocks: Vec<String> = Vec::new();
        let mut current: Option<Vec<&str>> = None;
        for line in text.lines() {
            match (&mut current, line.trim_end()) {
                (None, "```sql") => current = Some(Vec::new()),
                (Some(body), "```") => {
                    blocks.push(body.join("\n"));
                    current = None;
                }
                (Some(body), line) => body.push(line),
                (None, _) => {}
            }
        }
        assert_eq!(
            blocks.len(),
            1,
            "DESIGN.md should hold exactly one sql block, the §10 schema"
        );
        blocks.pop().expect("the §10 sql block")
    }

    /// Replaying MIGRATIONS yields exactly FINAL_SCHEMA object by object — which is DESIGN.md's §10 DDL, so the chain, the constant and the document cannot drift apart — and re-migrating changes nothing.
    #[test]
    fn the_chain_produces_the_documented_schema() {
        let mut chained = Connection::open_in_memory().unwrap();
        migrate(&mut chained, MIGRATIONS).unwrap();
        let documented = Connection::open_in_memory().unwrap();
        documented
            .execute_batch(crate::schema::FINAL_SCHEMA)
            .unwrap();
        let designed = Connection::open_in_memory().unwrap();
        designed
            .execute_batch(&design_schema())
            .expect("the §10 sql block must be executable DDL");
        let chained_objects = objects(&chained);
        assert_eq!(
            chained_objects,
            objects(&documented),
            "replaying the chain must yield exactly the documented §10 schema"
        );
        assert_eq!(
            objects(&designed),
            objects(&documented),
            "DESIGN.md §10 and FINAL_SCHEMA describe different databases"
        );
        assert!(
            !chained_objects.iter().any(|(_, name, _)| name == "want"),
            "the chain leaves nothing of the tables it retired behind"
        );
        // And re-opening a database at the current version changes nothing.
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path()).unwrap();
        let before = objects(&store.conn());
        drop(store);
        assert_eq!(objects(&Store::open(dir.path()).unwrap().conn()), before);
    }

    /// A database at the version each historical step left it at: exactly what replaying the first `v` steps produces, not an approximation.
    fn database_at(dir: &Path, version: u32) -> Connection {
        let mut conn = Connection::open(dir.join(DB_FILE)).unwrap();
        migrate(&mut conn, &MIGRATIONS[..version as usize]).unwrap();
        conn
    }

    /// A v2 database — the oldest layout still real — upgrades with its data intact: `want` drops, mirrors become pins, the s3 bucket map moves namespace, and observed heads from before v7 come through unclaimed.
    #[test]
    fn a_v2_database_upgrades_with_its_data() {
        let dir = tempfile::tempdir().unwrap();
        {
            let conn = database_at(dir.path(), 2);
            assert!(
                conn.query_row("SELECT COUNT(*) FROM want", [], |r| r.get::<_, i64>(0))
                    .is_ok(),
                "a v2 database still has the want table"
            );
            conn.execute(
                "INSERT INTO config (key, value) VALUES ('keep', 'me')",
                params![],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO mirrors (origin_id, space, local_path) VALUES (?1, ?2, ?3)",
                params!["nas@x.example", "media", "/mnt/nas"],
            )
            .unwrap();
            conn.execute(
                "INSERT INTO config (key, value) VALUES ('s3_buckets', ?1)",
                params!["photos\tnas@x.example\tmedia"],
            )
            .unwrap();
            conn.execute("INSERT INTO observed_heads (origin_id, seq, root, complete, observed_at) VALUES ('nas@x.example', 7, zeroblob(32), 1, 1)", params![]).unwrap();
        }
        let store = Store::open(dir.path()).unwrap();
        assert_eq!(
            store.config("schema_version").unwrap().as_deref(),
            Some(SCHEMA_VERSION.to_string().as_str())
        );
        assert!(
            store
                .conn()
                .query_row(
                    "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'want'",
                    [],
                    |_| Ok(())
                )
                .optional()
                .unwrap()
                .is_none(),
            "v3 drops it"
        );
        assert_eq!(store.config("keep").unwrap().as_deref(), Some("me"));
        // v4 carried the mirror over as an origin pin; v5 did the same for
        // the bucket map, and v8 moved it into the `s3.*` namespace.
        let mirrors = store.mirrors().unwrap();
        assert_eq!(mirrors.len(), 1);
        assert_eq!(mirrors[0].local_path, "/mnt/nas");
        assert_eq!(mirrors[0].space, "media");
        assert_eq!(mirrors[0].policy.render(), "origin=nas@x.example");
        assert_eq!(store.config("s3_buckets").unwrap(), None);
        assert_eq!(
            store.config("s3.buckets").unwrap().as_deref(),
            Some("photos\tmedia\torigin=nas@x.example")
        );
        let observed = store.observed_heads().unwrap();
        assert_eq!(observed.len(), 1);
        assert_eq!(observed[0].seq, 7);
        assert_eq!(
            observed[0].claimed_by, None,
            "an observation from before the column knows no claimant"
        );
    }

    /// v6 rebuilds `entries` to carry a symlink's target (§8 version identity), and every existing row comes through it, indexes included.
    #[test]
    fn a_v5_database_upgrades_with_its_entries() {
        let dir = tempfile::tempdir().unwrap();
        {
            let conn = database_at(dir.path(), 5);
            assert!(
                conn.query_row("SELECT symlink_target FROM entries", [], |r| r
                    .get::<_, Option<String>>(0))
                    .is_err(),
                "a v5 database has no target column"
            );
            conn.execute("INSERT INTO entries (origin_id, space, path, kind, size, mtime_ns, content, seq, prev) VALUES ('nas@x.example', 'media', 'a.txt', 0, 5, 42, zeroblob(32), 3, NULL)", params![]).unwrap();
        }
        let store = Store::open(dir.path()).unwrap();
        assert_eq!(
            store.config("schema_version").unwrap().as_deref(),
            Some(SCHEMA_VERSION.to_string().as_str())
        );
        let origin = OriginId::named("nas", "x.example").unwrap();
        let row = store.entry(&origin, "media", "a.txt").unwrap().unwrap();
        assert_eq!(row.size, 5);
        assert_eq!(row.mtime_ns, 42);
        assert_eq!(row.seq, 3);
        assert_eq!(row.symlink_target, None, "an existing file has no target");
        assert!(store
            .conn()
            .query_row(
                "SELECT 1 FROM sqlite_master WHERE type = 'index' AND name = 'entries_by_path'",
                [],
                |_| Ok(())
            )
            .is_ok());
    }

    /// A step that fails takes its whole transaction with it, stamp included, so the database is left at the version before it rather than between two — and the next open finishes the chain from there.
    #[test]
    fn a_failing_step_leaves_the_version_where_it_was() {
        let first: &[Migration] = &[
            Migration::Sql("CREATE TABLE config (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE first (a TEXT);"),
            Migration::Rust { name: "explodes", run: |_tx| Err(StoreError::invalid("boom")) },
            Migration::Sql("CREATE TABLE third (a TEXT);"),
        ];
        let mut conn = Connection::open_in_memory().unwrap();
        let err = migrate(&mut conn, first).unwrap_err().to_string();
        assert!(err.contains("explodes") && err.contains("boom"), "{err}");
        // Version 1 committed; the failing step's transaction rolled back
        // whole, so nothing it or the step after it would have created exists.
        let stamp: String = conn
            .query_row(
                "SELECT value FROM config WHERE key = 'schema_version'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(stamp, "1");
        assert!(conn
            .query_row("SELECT COUNT(*) FROM first", [], |r| r.get::<_, i64>(0))
            .is_ok());
        assert!(conn
            .query_row("SELECT COUNT(*) FROM third", [], |r| r.get::<_, i64>(0))
            .is_err());
        // Resuming from that version replays the rest of the chain, so a
        // crashed upgrade is finished by the next open rather than repaired.
        let fixed: &[Migration] = &[
            Migration::Sql("CREATE TABLE config (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE first (a TEXT);"),
            Migration::Sql("CREATE TABLE second (a TEXT);"),
            Migration::Sql("CREATE TABLE third (a TEXT);"),
        ];
        assert_eq!(migrate(&mut conn, fixed).unwrap(), 3);
        assert!(conn
            .query_row("SELECT COUNT(*) FROM third", [], |r| r.get::<_, i64>(0))
            .is_ok());
    }
}
