import VerifiedCore.Host.Codec
import VerifiedCore.Commands

/-! GENERATED by `hostgen` from the command and outcome types; do not edit. -/
namespace VerifiedCore
open Host.Wire

instance : Encode Cas.Codec.CellType where
  encode out value := match value with
    | .null => out.push 0
    | .integer => out.push 1
    | .real => out.push 2
    | .text => out.push 3
    | .blob => out.push 4

instance : Decode Cas.Codec.CellType where
  decode := do
    match ← readByte with
    | 0 => return .null
    | 1 => return .integer
    | 2 => return .real
    | 3 => return .text
    | 4 => return .blob
    | _ => throw ()

instance : Encode Cas.PinHolder where
  encode out value := match value with
    | .operator => out.push 0
    | .source a0 => out.push 1 |>.put a0
    | .replica a0 => out.push 2 |>.put a0
    | .other a0 => out.push 3 |>.put a0

instance : Decode Cas.PinHolder where
  decode := do
    match ← readByte with
    | 0 => return .operator
    | 1 => return .source (← Decode.decode)
    | 2 => return .replica (← Decode.decode)
    | 3 => return .other (← Decode.decode)
    | _ => throw ()

instance : Encode Cas.Input.Kind where
  encode out value := match value with
    | .bytes a0 => out.push 0 |>.put a0
    | .file => out.push 1

instance : Decode Cas.Input.Kind where
  decode := do
    match ← readByte with
    | 0 => return .bytes (← Decode.decode)
    | 1 => return .file
    | _ => throw ()

instance : Encode Cas.Outcome where
  encode out value := match value with
    | .skipped => out.push 0
    | .writing => out.push 1
    | .protectedClaim => out.push 2
    | .applied => out.push 3

instance : Decode Cas.Outcome where
  decode := do
    match ← readByte with
    | 0 => return .skipped
    | 1 => return .writing
    | 2 => return .protectedClaim
    | 3 => return .applied
    | _ => throw ()

instance : Encode Origin.Error where
  encode out value := match value with
    | .label a0 => out.push 0 |>.put a0
    | .domain a0 => out.push 1 |>.put a0
    | .keyDecode => out.push 2
    | .keyData => out.push 3
    | .shape a0 => out.push 4 |>.put a0

instance : Decode Origin.Error where
  decode := do
    match ← readByte with
    | 0 => return .label (← Decode.decode)
    | 1 => return .domain (← Decode.decode)
    | 2 => return .keyDecode
    | 3 => return .keyData
    | 4 => return .shape (← Decode.decode)
    | _ => throw ()

instance : Encode Trie.LookupError where
  encode out value := match value with
    | .keyTooLong a0 => out.push 0 |>.put a0
    | .missingNode a0 => out.push 1 |>.put a0
    | .missingValue a0 => out.push 2 |>.put a0
    | .decode a0 => out.push 3 |>.put a0
    | .depthExceeded => out.push 4

instance : Decode Trie.LookupError where
  decode := do
    match ← readByte with
    | 0 => return .keyTooLong (← Decode.decode)
    | 1 => return .missingNode (← Decode.decode)
    | 2 => return .missingValue (← Decode.decode)
    | 3 => return .decode (← Decode.decode)
    | 4 => return .depthExceeded
    | _ => throw ()

instance : Encode Trie.Refusal where
  encode out value := match value with
    | .decode a0 => out.push 0 |>.put a0
    | .nonCanonical a0 => out.push 1 |>.put a0
    | .keyTooLong a0 => out.push 2 |>.put a0

instance : Decode Trie.Refusal where
  decode := do
    match ← readByte with
    | 0 => return .decode (← Decode.decode)
    | 1 => return .nonCanonical (← Decode.decode)
    | 2 => return .keyTooLong (← Decode.decode)
    | _ => throw ()

instance : Encode Trie.Verdict where
  encode out value := match value with
    | .accepted => out.push 0
    | .originFault a0 => out.push 1 |>.put a0
    | .peerFault => out.push 2

instance : Decode Trie.Verdict where
  decode := do
    match ← readByte with
    | 0 => return .accepted
    | 1 => return .originFault (← Decode.decode)
    | 2 => return .peerFault
    | _ => throw ()

instance : Encode Trie.MutationError where
  encode out value := match value with
    | .keyTooLong a0 => out.push 0 |>.put a0
    | .valueTooLong a0 => out.push 1 |>.put a0
    | .missingNode a0 => out.push 2 |>.put a0
    | .decode a0 => out.push 3 |>.put a0
    | .depthExceeded => out.push 4

instance : Decode Trie.MutationError where
  decode := do
    match ← readByte with
    | 0 => return .keyTooLong (← Decode.decode)
    | 1 => return .valueTooLong (← Decode.decode)
    | 2 => return .missingNode (← Decode.decode)
    | 3 => return .decode (← Decode.decode)
    | 4 => return .depthExceeded
    | _ => throw ()

instance : Encode Cas.Receive.ProvenSubtree where
  encode out value := match value with
    | .mk a0 a1 a2 a3 => out |>.put a0 |>.put a1 |>.put a2 |>.put a3

instance : Decode Cas.Receive.ProvenSubtree where
  decode := do
    let a0 ← Decode.decode
    let a1 ← Decode.decode
    let a2 ← Decode.decode
    let a3 ← Decode.decode
    return .mk a0 a1 a2 a3

instance : Encode Commands.LifecycleDomainError where
  encode out value := match value with
    | .malformed => out.push 0
    | .columnType a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2

instance : Decode Commands.LifecycleDomainError where
  decode := do
    match ← readByte with
    | 0 => return .malformed
    | 1 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.IngestDomainError where
  encode out value := match value with
    | .malformed => out.push 0
    | .columnType a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2
    | .sizeMismatch a0 a1 a2 => out.push 2 |>.put a0 |>.put a1 |>.put a2
    | .directorySyncUnsupported => out.push 3

instance : Decode Commands.IngestDomainError where
  decode := do
    match ← readByte with
    | 0 => return .malformed
    | 1 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 2 => return .sizeMismatch (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 3 => return .directorySyncUnsupported
    | _ => throw ()

instance : Encode Commands.ReadDomainError where
  encode out value := match value with
    | .missingBlob => out.push 0
    | .range a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2
    | .unavailable => out.push 2
    | .shortInline => out.push 3
    | .malformed => out.push 4
    | .columnType a0 a1 a2 => out.push 5 |>.put a0 |>.put a1 |>.put a2
    | .column a0 a1 => out.push 6 |>.put a0 |>.put a1

instance : Decode Commands.ReadDomainError where
  decode := do
    match ← readByte with
    | 0 => return .missingBlob
    | 1 => return .range (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 2 => return .unavailable
    | 3 => return .shortInline
    | 4 => return .malformed
    | 5 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 6 => return .column (← Decode.decode) (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.HistoryDomainError where
  encode out value := match value with
    | .malformed => out.push 0
    | .columnType a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2
    | .invalidText a0 => out.push 2 |>.put a0
    | .column a0 a1 => out.push 3 |>.put a0 |>.put a1
    | .origin a0 => out.push 4 |>.put a0

instance : Decode Commands.HistoryDomainError where
  decode := do
    match ← readByte with
    | 0 => return .malformed
    | 1 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 2 => return .invalidText (← Decode.decode)
    | 3 => return .column (← Decode.decode) (← Decode.decode)
    | 4 => return .origin (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.DurableDomainError where
  encode out value := match value with
    | .malformed => out.push 0
    | .columnType a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2
    | .sizeMismatch a0 a1 a2 => out.push 2 |>.put a0 |>.put a1 |>.put a2

instance : Decode Commands.DurableDomainError where
  decode := do
    match ← readByte with
    | 0 => return .malformed
    | 1 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 2 => return .sizeMismatch (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.ServeDomainError where
  encode out value := match value with
    | .missingBlob => out.push 0
    | .malformed => out.push 1
    | .columnType a0 a1 a2 => out.push 2 |>.put a0 |>.put a1 |>.put a2
    | .column a0 a1 => out.push 3 |>.put a0 |>.put a1
    | .overBudget a0 a1 => out.push 4 |>.put a0 |>.put a1

instance : Decode Commands.ServeDomainError where
  decode := do
    match ← readByte with
    | 0 => return .missingBlob
    | 1 => return .malformed
    | 2 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 3 => return .column (← Decode.decode) (← Decode.decode)
    | 4 => return .overBudget (← Decode.decode) (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.ReceiveDomainError where
  encode out value := match value with
    | .malformed => out.push 0
    | .columnType a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2
    | .column a0 a1 => out.push 2 |>.put a0 |>.put a1
    | .sizeMismatch a0 a1 a2 => out.push 3 |>.put a0 |>.put a1 |>.put a2

instance : Decode Commands.ReceiveDomainError where
  decode := do
    match ← readByte with
    | 0 => return .malformed
    | 1 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 2 => return .column (← Decode.decode) (← Decode.decode)
    | 3 => return .sizeMismatch (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.CollectDomainError where
  encode out value := match value with
    | .malformed => out.push 0
    | .columnType a0 a1 a2 => out.push 1 |>.put a0 |>.put a1 |>.put a2
    | .sizeMismatch a0 a1 a2 => out.push 2 |>.put a0 |>.put a1 |>.put a2

instance : Decode Commands.CollectDomainError where
  decode := do
    match ← readByte with
    | 0 => return .malformed
    | 1 => return .columnType (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 2 => return .sizeMismatch (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | _ => throw ()

instance : Encode Commands.Ingested where
  encode out value := match value with
    | .mk a0 a1 => out |>.put a0 |>.put a1

instance : Decode Commands.Ingested where
  decode := do
    let a0 ← Decode.decode
    let a1 ← Decode.decode
    return .mk a0 a1

instance : Encode Commands.Committed where
  encode out value := match value with
    | .mk a0 a1 => out |>.put a0 |>.put a1

instance : Decode Commands.Committed where
  decode := do
    let a0 ← Decode.decode
    let a1 ← Decode.decode
    return .mk a0 a1

instance : Encode Commands.Served where
  encode out value := match value with
    | .mk a0 a1 => out |>.put a0 |>.put a1

instance : Decode Commands.Served where
  decode := do
    let a0 ← Decode.decode
    let a1 ← Decode.decode
    return .mk a0 a1

instance : Encode Commands.Evicted where
  encode out value := match value with
    | .mk a0 a1 => out |>.put a0 |>.put a1

instance : Decode Commands.Evicted where
  decode := do
    let a0 ← Decode.decode
    let a1 ← Decode.decode
    return .mk a0 a1

instance : Encode Commands.Command where
  encode out value := match value with
    | .acquire a0 a1 a2 a3 => out.push 0 |>.put a0 |>.put a1 |>.put a2 |>.put a3
    | .delete a0 a1 => out.push 1 |>.put a0 |>.put a1
    | .unpin a0 a1 => out.push 2 |>.put a0 |>.put a1
    | .expire a0 a1 => out.push 3 |>.put a0 |>.put a1
    | .read a0 a1 => out.push 4 |>.put a0 |>.put a1
    | .ingest a0 a1 a2 a3 => out.push 5 |>.put a0 |>.put a1 |>.put a2 |>.put a3
    | .commitGroups a0 a1 a2 a3 a4 a5 => out.push 6 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4 |>.put a5
    | .admitSize a0 a1 => out.push 7 |>.put a0 |>.put a1
    | .trieGet a0 a1 => out.push 8 |>.put a0 |>.put a1
    | .trieAdmit a0 => out.push 9 |>.put a0
    | .trieVerify a0 a1 => out.push 10 |>.put a0 |>.put a1
    | .trieInsert a0 a1 a2 => out.push 11 |>.put a0 |>.put a1 |>.put a2
    | .trieRemove a0 a1 => out.push 12 |>.put a0 |>.put a1
    | .pruneHistory a0 a1 => out.push 13 |>.put a0 |>.put a1
    | .casMarkDurable a0 => out.push 14 |>.put a0
    | .casAdoptDurable a0 a1 a2 => out.push 15 |>.put a0 |>.put a1 |>.put a2
    | .casHealMissing a0 => out.push 16 |>.put a0
    | .casReconcileScratch a0 => out.push 17 |>.put a0
    | .casClearCache a0 => out.push 18 |>.put a0
    | .casEncodeSlice a0 a1 => out.push 19 |>.put a0 |>.put a1
    | .casEncodeProof a0 a1 a2 a3 => out.push 20 |>.put a0 |>.put a1 |>.put a2 |>.put a3
    | .casWriteSlice a0 a1 a2 a3 a4 => out.push 21 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
    | .casWriteProof a0 a1 a2 a3 a4 a5 => out.push 22 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4 |>.put a5
    | .casPromote a0 a1 a2 a3 a4 a5 => out.push 23 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4 |>.put a5
    | .casTouch a0 => out.push 24 |>.put a0
    | .casEvict a0 a1 => out.push 25 |>.put a0 |>.put a1
    | .casGcContent a0 => out.push 26 |>.put a0
    | .casGcOrphans a0 => out.push 27 |>.put a0

instance : Decode Commands.Command where
  decode := do
    match ← readByte with
    | 0 => return .acquire (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 1 => return .delete (← Decode.decode) (← Decode.decode)
    | 2 => return .unpin (← Decode.decode) (← Decode.decode)
    | 3 => return .expire (← Decode.decode) (← Decode.decode)
    | 4 => return .read (← Decode.decode) (← Decode.decode)
    | 5 => return .ingest (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 6 => return .commitGroups (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 7 => return .admitSize (← Decode.decode) (← Decode.decode)
    | 8 => return .trieGet (← Decode.decode) (← Decode.decode)
    | 9 => return .trieAdmit (← Decode.decode)
    | 10 => return .trieVerify (← Decode.decode) (← Decode.decode)
    | 11 => return .trieInsert (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 12 => return .trieRemove (← Decode.decode) (← Decode.decode)
    | 13 => return .pruneHistory (← Decode.decode) (← Decode.decode)
    | 14 => return .casMarkDurable (← Decode.decode)
    | 15 => return .casAdoptDurable (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 16 => return .casHealMissing (← Decode.decode)
    | 17 => return .casReconcileScratch (← Decode.decode)
    | 18 => return .casClearCache (← Decode.decode)
    | 19 => return .casEncodeSlice (← Decode.decode) (← Decode.decode)
    | 20 => return .casEncodeProof (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 21 => return .casWriteSlice (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 22 => return .casWriteProof (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 23 => return .casPromote (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode) (← Decode.decode)
    | 24 => return .casTouch (← Decode.decode)
    | 25 => return .casEvict (← Decode.decode) (← Decode.decode)
    | 26 => return .casGcContent (← Decode.decode)
    | 27 => return .casGcOrphans (← Decode.decode)
    | _ => throw ()

end VerifiedCore
