import VerifiedCore.Host.Codec
import VerifiedCore.Crypto
import VerifiedCore.Host.Construct
import VerifiedCore.Host.Source
import VerifiedCore.Host.Digest
import VerifiedCore.Host.Writes
import VerifiedCore.Host.Bao
import VerifiedCore.Host.Sweep
import VerifiedCore.Host.Memo
import VerifiedCore.Host.Walk
import VerifiedCore.Host.Peer
import VerifiedCore.Host.Provider
import VerifiedCore.Host.CacheIO

/-! GENERATED by `hostgen` from the effect algebras; do not edit. Each
algebra's tags, names, request encoder, reply decoder and `WireEffect`
instance follow from its constructors and the tag table. -/
namespace VerifiedCore.Host
open Wire

def Storage.tag : Storage A → UInt8
  | .begin => 16
  | .commit _ => 17
  | .rollback _ => 18
  | .readRows _ _ _ _ _ _ => 19
  | .scanRows _ _ _ _ _ _ => 28
  | .upsert _ _ _ _ _ => 20
  | .deleteRows _ _ _ _ _ => 21
  | .deleteExcept _ _ _ _ => 68
  | .readBytes _ _ => 22
  | .readInput _ _ _ => 23
  | .readCounter _ _ => 24
  | .removeFile _ _ => 25
  | .existsRows _ _ _ => 26

def Storage.name : Storage A → String
  | .begin => "begin"
  | .commit _ => "commit"
  | .rollback _ => "rollback"
  | .readRows _ _ _ _ _ _ => "readRows"
  | .scanRows _ _ _ _ _ _ => "scanRows"
  | .upsert _ _ _ _ _ => "upsert"
  | .deleteRows _ _ _ _ _ => "deleteRows"
  | .deleteExcept _ _ _ _ => "deleteExcept"
  | .readBytes _ _ => "readBytes"
  | .readInput _ _ _ => "readInput"
  | .readCounter _ _ => "readCounter"
  | .removeFile _ _ => "removeFile"
  | .existsRows _ _ _ => "existsRows"

def Storage.request : Storage A → ByteArray
  | .begin => header 16
  | .commit a0 => header 17 |>.put a0
  | .rollback a0 => header 18 |>.put a0
  | .readRows a0 a1 a2 a3 a4 a5 => header 19 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4 |>.put a5
  | .scanRows a0 a1 a2 a3 a4 a5 => header 28 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4 |>.put a5
  | .upsert a0 a1 a2 a3 a4 => header 20 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
  | .deleteRows a0 a1 a2 a3 a4 => header 21 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
  | .deleteExcept a0 a1 a2 a3 => header 68 |>.put a0 |>.put a1 |>.put a2 |>.put a3
  | .readBytes a0 a1 => header 22 |>.put a0 |>.put a1
  | .readInput a0 a1 a2 => header 23 |>.put a0 |>.put a1 |>.put a2
  | .readCounter a0 a1 => header 24 |>.put a0 |>.put a1
  | .removeFile a0 a1 => header 25 |>.put a0 |>.put a1
  | .existsRows a0 a1 a2 => header 26 |>.put a0 |>.put a1 |>.put a2

def Storage.reply (effect : Storage A) (input : ByteArray) : A :=
  match effect with
  | .begin => decodeReply 16 Decode.decode input
  | .commit _ => decodeReply 17 Decode.decode input
  | .rollback _ => decodeReply 18 Decode.decode input
  | .readRows _ _ _ _ _ _ => decodeReply 19 Decode.decode input
  | .scanRows _ _ _ _ _ _ => decodeReply 28 Decode.decode input
  | .upsert _ _ _ _ _ => decodeReply 20 Decode.decode input
  | .deleteRows _ _ _ _ _ => decodeReply 21 Decode.decode input
  | .deleteExcept _ _ _ _ => decodeReply 68 Decode.decode input
  | .readBytes _ _ => decodeReply 22 Decode.decode input
  | .readInput _ _ _ => decodeReply 23 Decode.decode input
  | .readCounter _ _ => decodeReply 24 Decode.decode input
  | .removeFile _ _ => decodeReply 25 Decode.decode input
  | .existsRows _ _ _ => decodeReply 26 Decode.decode input

instance : WireEffect Storage := ⟨Storage.request, Storage.reply⟩

def Crypto.tag : Crypto A → UInt8
  | .validateEd25519 _ => 27

def Crypto.name : Crypto A → String
  | .validateEd25519 _ => "validateEd25519"

def Crypto.request : Crypto A → ByteArray
  | .validateEd25519 a0 => header 27 |>.put a0

def Crypto.reply (effect : Crypto A) (input : ByteArray) : A :=
  match effect with
  | .validateEd25519 _ => decodeReply 27 Decode.decode input

instance : WireEffect Crypto := ⟨Crypto.request, Crypto.reply⟩

def Access.tag : Access A → UInt8
  | .snapshot _ _ => 29
  | .snapshotExcluding _ _ _ => 64
  | .update _ _ _ => 30
  | .copyRows _ _ _ _ _ => 31
  | .delete _ _ => 32

def Access.name : Access A → String
  | .snapshot _ _ => "snapshot"
  | .snapshotExcluding _ _ _ => "snapshotExcluding"
  | .update _ _ _ => "update"
  | .copyRows _ _ _ _ _ => "copyRows"
  | .delete _ _ => "delete"

def Access.request : Access A → ByteArray
  | .snapshot a0 a1 => header 29 |>.put a0 |>.put a1
  | .snapshotExcluding a0 a1 a2 => header 64 |>.put a0 |>.put a1 |>.put a2
  | .update a0 a1 a2 => header 30 |>.put a0 |>.put a1 |>.put a2
  | .copyRows a0 a1 a2 a3 a4 => header 31 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
  | .delete a0 a1 => header 32 |>.put a0 |>.put a1

def Access.reply (effect : Access A) (input : ByteArray) : A :=
  match effect with
  | .snapshot _ _ => decodeReply 29 Decode.decode input
  | .snapshotExcluding _ _ _ => decodeReply 64 Decode.decode input
  | .update _ _ _ => decodeReply 30 Decode.decode input
  | .copyRows _ _ _ _ _ => decodeReply 31 Decode.decode input
  | .delete _ _ => decodeReply 32 Decode.decode input

instance : WireEffect Access := ⟨Access.request, Access.reply⟩

def FileIO.tag : FileIO A → UInt8
  | .open _ _ => 33
  | .readAt _ _ _ => 34
  | .transfer _ _ _ => 52
  | .close _ => 35

def FileIO.name : FileIO A → String
  | .open _ _ => "open"
  | .readAt _ _ _ => "readAt"
  | .transfer _ _ _ => "transfer"
  | .close _ => "close"

def FileIO.request : FileIO A → ByteArray
  | .open a0 a1 => header 33 |>.put a0 |>.put a1
  | .readAt a0 a1 a2 => header 34 |>.put a0 |>.put a1 |>.put a2
  | .transfer a0 a1 a2 => header 52 |>.put a0 |>.put a1 |>.put a2
  | .close a0 => header 35 |>.put a0

def FileIO.reply (effect : FileIO A) (input : ByteArray) : A :=
  match effect with
  | .open _ _ => decodeFileReply 33 Decode.decode input
  | .readAt _ _ _ => decodeFileReply 34 Decode.decode input
  | .transfer _ _ _ => decodeFileReply 52 Decode.decode input
  | .close _ => decodeReply 35 Decode.decode input

instance : WireEffect FileIO := ⟨FileIO.request, FileIO.reply⟩

def Clock.tag : Clock A → UInt8
  | .nowNs => 36

def Clock.name : Clock A → String
  | .nowNs => "nowNs"

def Clock.request : Clock A → ByteArray
  | .nowNs => header 36

def Clock.reply (effect : Clock A) (input : ByteArray) : A :=
  match effect with
  | .nowNs => decodeReply 36 Decode.decode input

instance : WireEffect Clock := ⟨Clock.request, Clock.reply⟩

def Output.tag : Output A → UInt8
  | .append _ => 37

def Output.name : Output A → String
  | .append _ => "append"

def Output.request : Output A → ByteArray
  | .append a0 => header 37 |>.put a0

def Output.reply (effect : Output A) (input : ByteArray) : A :=
  match effect with
  | .append _ => decodeReply 37 Decode.decode input

instance : WireEffect Output := ⟨Output.request, Output.reply⟩

def Construct.tag : Construct A → UInt8
  | .build _ _ _ _ => 38
  | .hash _ => 39

def Construct.name : Construct A → String
  | .build _ _ _ _ => "build"
  | .hash _ => "hash"

def Construct.request : Construct A → ByteArray
  | .build a0 a1 a2 a3 => header 38 |>.put a0 |>.put a1 |>.put a2 |>.put a3
  | .hash a0 => header 39 |>.put a0

def Construct.reply (effect : Construct A) (input : ByteArray) : A :=
  match effect with
  | .build _ _ _ _ => decodeReply 38 Decode.decode input
  | .hash _ => decodeReply 39 Decode.decode input

instance : WireEffect Construct := ⟨Construct.request, Construct.reply⟩

def Upsert.tag : Upsert A → UInt8
  | .write _ _ _ _ _ => 41

def Upsert.name : Upsert A → String
  | .write _ _ _ _ _ => "write"

def Upsert.request : Upsert A → ByteArray
  | .write a0 a1 a2 a3 a4 => header 41 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4

def Upsert.reply (effect : Upsert A) (input : ByteArray) : A :=
  match effect with
  | .write _ _ _ _ _ => decodeReply 41 Decode.decode input

instance : WireEffect Upsert := ⟨Upsert.request, Upsert.reply⟩

def Resources.tag : Resources A → UInt8
  | .createTemporary _ => 42
  | .flush _ => 43
  | .replace _ _ _ => 44
  | .discard _ => 45
  | .syncParent _ _ => 46

def Resources.name : Resources A → String
  | .createTemporary _ => "createTemporary"
  | .flush _ => "flush"
  | .replace _ _ _ => "replace"
  | .discard _ => "discard"
  | .syncParent _ _ => "syncParent"

def Resources.request : Resources A → ByteArray
  | .createTemporary a0 => header 42 |>.put a0
  | .flush a0 => header 43 |>.put a0
  | .replace a0 a1 a2 => header 44 |>.put a0 |>.put a1 |>.put a2
  | .discard a0 => header 45 |>.put a0
  | .syncParent a0 a1 => header 46 |>.put a0 |>.put a1

def Resources.reply (effect : Resources A) (input : ByteArray) : A :=
  match effect with
  | .createTemporary _ => decodeReply 42 Decode.decode input
  | .flush _ => decodeReply 43 Decode.decode input
  | .replace _ _ _ => decodeReply 44 Decode.decode input
  | .discard _ => decodeReply 45 Decode.decode input
  | .syncParent _ _ => decodeReply 46 Decode.decode input

instance : WireEffect Resources := ⟨Resources.request, Resources.reply⟩

def Lease.tag : Lease A → UInt8
  | .acquire _ _ => 47
  | .order _ => 63
  | .release _ => 48

def Lease.name : Lease A → String
  | .acquire _ _ => "acquire"
  | .order _ => "order"
  | .release _ => "release"

def Lease.request : Lease A → ByteArray
  | .acquire a0 a1 => header 47 |>.put a0 |>.put a1
  | .order a0 => header 63 |>.put a0
  | .release a0 => header 48 |>.put a0

def Lease.reply (effect : Lease A) (input : ByteArray) : A :=
  match effect with
  | .acquire _ _ => decodeReply 47 Decode.decode input
  | .order _ => decodeReply 63 Decode.decode input
  | .release _ => decodeReply 48 Decode.decode input

instance : WireEffect Lease := ⟨Lease.request, Lease.reply⟩

def SourceIO.tag : SourceIO A → UInt8
  | .stat _ _ => 49
  | .readSome _ _ _ => 50
  | .freeze _ => 51

def SourceIO.name : SourceIO A → String
  | .stat _ _ => "stat"
  | .readSome _ _ _ => "readSome"
  | .freeze _ => "freeze"

def SourceIO.request : SourceIO A → ByteArray
  | .stat a0 a1 => header 49 |>.put a0 |>.put a1
  | .readSome a0 a1 a2 => header 50 |>.put a0 |>.put a1 |>.put a2
  | .freeze a0 => header 51 |>.put a0

def SourceIO.reply (effect : SourceIO A) (input : ByteArray) : A :=
  match effect with
  | .stat _ _ => decodeReply 49 Decode.decode input
  | .readSome _ _ _ => decodeReply 50 Decode.decode input
  | .freeze _ => decodeReply 51 Decode.decode input

instance : WireEffect SourceIO := ⟨SourceIO.request, SourceIO.reply⟩

def Digest.tag : Digest A → UInt8
  | .blake3 _ => 53

def Digest.name : Digest A → String
  | .blake3 _ => "blake3"

def Digest.request : Digest A → ByteArray
  | .blake3 a0 => header 53 |>.put a0

def Digest.reply (effect : Digest A) (input : ByteArray) : A :=
  match effect with
  | .blake3 _ => decodeReply 53 Decode.decode input

instance : WireEffect Digest := ⟨Digest.request, Digest.reply⟩

def ByteWrites.tag : ByteWrites A → UInt8
  | .putBytes _ _ _ => 54

def ByteWrites.name : ByteWrites A → String
  | .putBytes _ _ _ => "putBytes"

def ByteWrites.request : ByteWrites A → ByteArray
  | .putBytes a0 a1 a2 => header 54 |>.put a0 |>.put a1 |>.put a2

def ByteWrites.reply (effect : ByteWrites A) (input : ByteArray) : A :=
  match effect with
  | .putBytes _ _ _ => decodeReply 54 Decode.decode input

instance : WireEffect ByteWrites := ⟨ByteWrites.request, ByteWrites.reply⟩

def Bao.tag : Bao A → UInt8
  | .encodeSlice _ _ _ _ => 55
  | .encodeProof _ _ _ _ _ => 56
  | .decodeInline _ _ _ _ _ => 57
  | .decodeSlice _ _ _ _ => 58
  | .flushObject _ => 59
  | .trimObject _ _ => 60
  | .writeProof _ _ _ _ _ => 61
  | .promoteRun _ _ _ _ _ _ => 62

def Bao.name : Bao A → String
  | .encodeSlice _ _ _ _ => "encodeSlice"
  | .encodeProof _ _ _ _ _ => "encodeProof"
  | .decodeInline _ _ _ _ _ => "decodeInline"
  | .decodeSlice _ _ _ _ => "decodeSlice"
  | .flushObject _ => "flushObject"
  | .trimObject _ _ => "trimObject"
  | .writeProof _ _ _ _ _ => "writeProof"
  | .promoteRun _ _ _ _ _ _ => "promoteRun"

def Bao.request : Bao A → ByteArray
  | .encodeSlice a0 a1 a2 a3 => header 55 |>.put a0 |>.put a1 |>.put a2 |>.put a3
  | .encodeProof a0 a1 a2 a3 a4 => header 56 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
  | .decodeInline a0 a1 a2 a3 a4 => header 57 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
  | .decodeSlice a0 a1 a2 a3 => header 58 |>.put a0 |>.put a1 |>.put a2 |>.put a3
  | .flushObject a0 => header 59 |>.put a0
  | .trimObject a0 a1 => header 60 |>.put a0 |>.put a1
  | .writeProof a0 a1 a2 a3 a4 => header 61 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4
  | .promoteRun a0 a1 a2 a3 a4 a5 => header 62 |>.put a0 |>.put a1 |>.put a2 |>.put a3 |>.put a4 |>.put a5

def Bao.reply (effect : Bao A) (input : ByteArray) : A :=
  match effect with
  | .encodeSlice _ _ _ _ => decodeReply 55 Decode.decode input
  | .encodeProof _ _ _ _ _ => decodeReply 56 Decode.decode input
  | .decodeInline _ _ _ _ _ => decodeReply 57 Decode.decode input
  | .decodeSlice _ _ _ _ => decodeReply 58 Decode.decode input
  | .flushObject _ => decodeReply 59 Decode.decode input
  | .trimObject _ _ => decodeReply 60 Decode.decode input
  | .writeProof _ _ _ _ _ => decodeReply 61 Decode.decode input
  | .promoteRun _ _ _ _ _ _ => decodeReply 62 Decode.decode input

instance : WireEffect Bao := ⟨Bao.request, Bao.reply⟩

def Sweep.tag : Sweep A → UInt8
  | .fileBytes _ _ => 65
  | .fileModified _ _ => 66
  | .listObjects _ => 67

def Sweep.name : Sweep A → String
  | .fileBytes _ _ => "fileBytes"
  | .fileModified _ _ => "fileModified"
  | .listObjects _ => "listObjects"

def Sweep.request : Sweep A → ByteArray
  | .fileBytes a0 a1 => header 65 |>.put a0 |>.put a1
  | .fileModified a0 a1 => header 66 |>.put a0 |>.put a1
  | .listObjects a0 => header 67 |>.put a0

def Sweep.reply (effect : Sweep A) (input : ByteArray) : A :=
  match effect with
  | .fileBytes _ _ => decodeReply 65 Decode.decode input
  | .fileModified _ _ => decodeReply 66 Decode.decode input
  | .listObjects _ => decodeReply 67 Decode.decode input

instance : WireEffect Sweep := ⟨Sweep.request, Sweep.reply⟩

def Memo.tag : Memo A → UInt8
  | .forgetExcept _ => 69
  | .isKnown _ => 74
  | .generation => 75
  | .certify _ _ => 76

def Memo.name : Memo A → String
  | .forgetExcept _ => "forgetExcept"
  | .isKnown _ => "isKnown"
  | .generation => "generation"
  | .certify _ _ => "certify"

def Memo.request : Memo A → ByteArray
  | .forgetExcept a0 => header 69 |>.put a0
  | .isKnown a0 => header 74 |>.put a0
  | .generation => header 75
  | .certify a0 a1 => header 76 |>.put a0 |>.put a1

def Memo.reply (effect : Memo A) (input : ByteArray) : A :=
  match effect with
  | .forgetExcept _ => decodeReply 69 Decode.decode input
  | .isKnown _ => decodeReply 74 Decode.decode input
  | .generation => decodeReply 75 Decode.decode input
  | .certify _ _ => decodeReply 76 Decode.decode input

instance : WireEffect Memo := ⟨Memo.request, Memo.reply⟩

def Redaction.tag : Redaction A → UInt8
  | .isRedacted _ _ => 70

def Redaction.name : Redaction A → String
  | .isRedacted _ _ => "isRedacted"

def Redaction.request : Redaction A → ByteArray
  | .isRedacted a0 a1 => header 70 |>.put a0 |>.put a1

def Redaction.reply (effect : Redaction A) (input : ByteArray) : A :=
  match effect with
  | .isRedacted _ _ => decodeReply 70 Decode.decode input

instance : WireEffect Redaction := ⟨Redaction.request, Redaction.reply⟩

def Apply.tag : Apply A → UInt8
  | .applyChange _ _ _ => 71

def Apply.name : Apply A → String
  | .applyChange _ _ _ => "applyChange"

def Apply.request : Apply A → ByteArray
  | .applyChange a0 a1 a2 => header 71 |>.put a0 |>.put a1 |>.put a2

def Apply.reply (effect : Apply A) (input : ByteArray) : A :=
  match effect with
  | .applyChange _ _ _ => decodeReply 71 Decode.decode input

instance : WireEffect Apply := ⟨Apply.request, Apply.reply⟩

def Peer.tag : Peer A → UInt8
  | .fetchNodes _ _ => 72
  | .fetchValues _ _ => 73

def Peer.name : Peer A → String
  | .fetchNodes _ _ => "fetchNodes"
  | .fetchValues _ _ => "fetchValues"

def Peer.request : Peer A → ByteArray
  | .fetchNodes a0 a1 => header 72 |>.put a0 |>.put a1
  | .fetchValues a0 a1 => header 73 |>.put a0 |>.put a1

def Peer.reply (effect : Peer A) (input : ByteArray) : A :=
  match effect with
  | .fetchNodes _ _ => decodeReply 72 Decode.decode input
  | .fetchValues _ _ => decodeReply 73 Decode.decode input

instance : WireEffect Peer := ⟨Peer.request, Peer.reply⟩

def Provider.tag : Provider A → UInt8
  | .stat _ _ => 77
  | .readAll _ _ => 78
  | .readRange _ _ _ _ => 79

def Provider.name : Provider A → String
  | .stat _ _ => "stat"
  | .readAll _ _ => "readAll"
  | .readRange _ _ _ _ => "readRange"

def Provider.request : Provider A → ByteArray
  | .stat a0 a1 => header 77 |>.put a0 |>.put a1
  | .readAll a0 a1 => header 78 |>.put a0 |>.put a1
  | .readRange a0 a1 a2 a3 => header 79 |>.put a0 |>.put a1 |>.put a2 |>.put a3

def Provider.reply (effect : Provider A) (input : ByteArray) : A :=
  match effect with
  | .stat _ _ => decodeFileReply 77 Decode.decode input
  | .readAll _ _ => decodeFileReply 78 Decode.decode input
  | .readRange _ _ _ _ => decodeFileReply 79 Decode.decode input

instance : WireEffect Provider := ⟨Provider.request, Provider.reply⟩

def CacheIO.tag : CacheIO A → UInt8
  | .isFile _ _ => 80
  | .writeAt _ _ _ _ => 81
  | .flush _ _ => 82
  | .writeTemporary _ _ _ => 83

def CacheIO.name : CacheIO A → String
  | .isFile _ _ => "isFile"
  | .writeAt _ _ _ _ => "writeAt"
  | .flush _ _ => "flush"
  | .writeTemporary _ _ _ => "writeTemporary"

def CacheIO.request : CacheIO A → ByteArray
  | .isFile a0 a1 => header 80 |>.put a0 |>.put a1
  | .writeAt a0 a1 a2 a3 => header 81 |>.put a0 |>.put a1 |>.put a2 |>.put a3
  | .flush a0 a1 => header 82 |>.put a0 |>.put a1
  | .writeTemporary a0 a1 a2 => header 83 |>.put a0 |>.put a1 |>.put a2

def CacheIO.reply (effect : CacheIO A) (input : ByteArray) : A :=
  match effect with
  | .isFile _ _ => decodeReply 80 Decode.decode input
  | .writeAt _ _ _ _ => decodeReply 81 Decode.decode input
  | .flush _ _ => decodeReply 82 Decode.decode input
  | .writeTemporary _ _ _ => decodeReply 83 Decode.decode input

instance : WireEffect CacheIO := ⟨CacheIO.request, CacheIO.reply⟩

end VerifiedCore.Host
